// Writes `build/colbin.wasm` into `src/generated/wasm-inline.ts` as one base64
// string — PACKAGE_PLAN.md §7.
//
// The generated file is gitignored and regenerated by the build, which is the
// point: the base64 cannot drift from the `.wasm` beside it, because nothing
// ever commits a copy of either.

import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const source = join(root, 'build', 'colbin.wasm')
const target = join(root, 'src', 'generated', 'wasm-inline.ts')

const wasm = await readFile(source).catch((err) => {
  throw new Error(`no module at ${source}: run \`bun run wasm\` first (${err.code})`)
})

const base64 = wasm.toString('base64')

const file = `// Generated by scripts/inline.mjs from build/colbin.wasm. Do not edit, and do
// not commit: \`bun run build\` rewrites it, which is what keeps these bytes
// and the \`.wasm\` from drifting apart.
//
// ${wasm.length} bytes of module, ${base64.length} of base64.
export const wasmBase64 =
  '${base64}'
`

await mkdir(dirname(target), { recursive: true })
await writeFile(target, file)

const kb = (n) => `${(n / 1024).toFixed(1)} KB`
console.log(`inlined ${kb(wasm.length)} of module as ${kb(base64.length)} of base64`)
