//! Inference and the section writer, against committed bytes.
//!
//! `js/vectors/web_encoded.json` holds, for each of the documents in
//! `js/tests/documents.mjs`, the JSON text that went in and the schema section
//! that came out. So this file parses the same text, infers a schema from it,
//! writes the section, and asserts the bytes are identical.
//!
//! That is the oracle discipline `RUST_WASM_PLAN.md` §4 asks for, and byte
//! equality is the only check available for this layer: inference is not in Go,
//! so there is nothing to diff against but a record of what was agreed.
//! `rust/ENCODER.md` states the rules, this pins them, and the two have to be
//! changed together — a rule edited in the prose and not here is a rule nothing
//! enforces.
//!
//! The file was written by the AssemblyScript module `RUST_WASM_PLAN.md` phase 8
//! deleted, and this port reproduces it byte for byte, which is what made the
//! deletion safe. It is regenerated by `bun run emit` in `js/` and CI fails on
//! a diff, so it now moves only when someone means it to.

#![cfg(feature = "encode")]

use colbin::diag::{D_CONFLICT, D_UNSUPPORTED, Diag};
use colbin::infer;
use colbin::json::parse;
use colbin::plan::{OP_INT64, OP_POINTER, OP_STRING, OP_STRINGS, OP_STRUCTS};
use colbin::section;

fn oracle() -> serde_json::Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../js/vectors/web_encoded.json"
    );
    let text = std::fs::read_to_string(path).expect("web_encoded.json — run `bun run emit` in js/");
    serde_json::from_str(&text).expect("web_encoded.json is not JSON")
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Parses and infers, returning the schema or the diagnostic.
fn schema_of(text: &str) -> Result<infer::Inferred, Diag> {
    let mut diag = Diag::new();
    let Some(doc) = parse::parse(text.as_bytes(), &mut diag) else {
        diag.locate(text.as_bytes());
        return Err(diag);
    };
    match infer::infer(&doc, &mut diag) {
        Some(inferred) => Ok(inferred),
        None => {
            diag.locate(text.as_bytes());
            Err(diag)
        }
    }
}

#[test]
fn every_document_infers_the_section_the_module_wrote() {
    let corpus = oracle();
    let cases = corpus["cases"].as_array().expect("cases");
    assert!(cases.len() >= 40, "corpus shrank: {} cases", cases.len());

    for case in cases {
        let name = case["name"].as_str().expect("name");
        let input = case["input"].as_str().expect("input");
        let want = case["section"].as_str().expect("section");

        let inferred = schema_of(input).unwrap_or_else(|e| panic!("{name}: {}", e.message));
        let got = hex(&section::build(&inferred.schema));
        assert_eq!(got, want, "{name}: the section differs\n  input: {input}");
    }
}

/// The other direction, and the one that pins the writer to Go rather than to
/// the module: every section in the Go-written corpus, parsed and written back.
/// A writer that agreed with the reader but not with the format would pass the
/// test above and fail this one.
#[test]
fn every_go_written_section_round_trips_to_the_same_bytes() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/vectors/vectors.json");
    let text = std::fs::read_to_string(path).expect("vectors.json");
    let corpus: serde_json::Value = serde_json::from_str(&text).expect("vectors.json is not JSON");

    let mut checked = 0;
    for case in corpus["walks"].as_array().expect("walks") {
        let name = case["name"].as_str().expect("name");
        let want = case["section"].as_str().expect("section");
        let bytes: Vec<u8> = (0..want.len())
            .step_by(2)
            .map(|at| u8::from_str_radix(&want[at..at + 2], 16).expect("hex"))
            .collect();

        let schema = section::parse(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(hex(&section::build(&schema)), want, "{name}");
        checked += 1;
    }
    assert!(checked >= 48, "only {checked} sections round-tripped");
}

#[test]
fn a_flat_object_numbers_its_fields_in_first_seen_order() {
    let inferred = schema_of(r#"{"id":1,"name":"x","price":2,"active":true}"#).expect("infer");
    let root = inferred.schema.root();
    assert_eq!(root.names, ["id", "name", "price", "active"]);
    assert_eq!(
        root.fields.iter().map(|f| f.key).collect::<Vec<_>>(),
        [0, 1, 2, 3],
        "sequential, not hashed: that is what keeps the keys narrow",
    );
    assert!(!root.is_wide);
    assert!(!root.is_envelope);
}

#[test]
fn seventeen_fields_is_where_the_keys_go_wide() {
    let of = |count: usize| {
        let fields: String = (0..count).map(|at| format!("\"f{at}\":{at},")).collect();
        format!("{{{fields}\"last\":1}}")
    };
    // Sixteen numbered fields plus `last` is seventeen, which four key bits
    // cannot hold; fifteen plus `last` is sixteen, which is exactly what they do.
    assert!(schema_of(&of(16)).expect("infer").schema.root().is_wide);
    assert!(!schema_of(&of(15)).expect("infer").schema.root().is_wide);
}

#[test]
fn a_non_object_root_is_wrapped_in_the_envelope_go_also_writes() {
    for text in ["42", r#""hello""#, "[1,2,3]", r#"[{"a":1}]"#] {
        let inferred = schema_of(text).expect("infer");
        let root = inferred.schema.root();
        assert!(root.is_envelope, "{text}");
        assert_eq!(root.names, ["rows"], "{text}");
        assert_eq!(root.fields.len(), 1, "{text}");
    }
}

/// The struct table is a pre-order walk, which is what makes a section written
/// here the bytes a reader's own hoisting would have produced.
#[test]
fn nested_structs_are_hoisted_root_first() {
    let inferred = schema_of(r#"{"a":{"b":{"c":1}},"d":{"e":2}}"#).expect("infer");
    let plans = &inferred.schema.plans;
    assert_eq!(plans.len(), 4, "root, a, a.b, d");
    assert_eq!(plans[0].names, ["a", "d"]);
    assert_eq!(plans[1].names, ["b"]);
    assert_eq!(plans[2].names, ["c"]);
    assert_eq!(plans[3].names, ["e"]);
    assert_eq!(plans[0].fields[0].sub, Some(1));
    assert_eq!(plans[0].fields[1].sub, Some(3));
}

/// A key absent from one record is indistinguishable from an explicit null, and
/// both make the field a pointer — so the two records stay distinguishable.
#[test]
fn a_missing_key_and_an_explicit_null_both_become_pointers() {
    for text in [
        r#"[{"id":1,"note":"hi"},{"id":2}]"#,
        r#"[{"id":1,"note":"hi"},{"id":2,"note":null}]"#,
    ] {
        let inferred = schema_of(text).expect("infer");
        // The envelope's one field points at the record struct.
        let record = inferred.schema.plan(1).expect("the record struct");
        assert_eq!(record.names, ["id", "note"], "{text}");
        assert_eq!(record.fields[1].op, OP_POINTER, "{text}");
        assert_eq!(record.fields[1].elem_op, OP_STRING, "{text}");
    }
}

#[test]
fn one_float_promotes_the_whole_column() {
    let inferred = schema_of(r#"[{"v":1},{"v":2.5},{"v":3}]"#).expect("infer");
    let record = inferred.schema.plan(1).expect("the record struct");
    assert_eq!(record.fields[0].op, colbin::plan::OP_FLOAT64);
}

#[test]
fn an_integer_past_the_int64_maximum_takes_the_unsigned_column() {
    let inferred = schema_of(r#"{"v":18446744073709551615}"#).expect("infer");
    assert_eq!(inferred.schema.root().fields[0].op, colbin::plan::OP_UINT64);
}

#[test]
fn array_element_types_resolve_to_the_ops_the_format_has() {
    let inferred = schema_of(r#"{"ints":[1,2],"strings":["a"],"rows":[{"q":1}]}"#).expect("infer");
    let root = inferred.schema.root();
    assert_eq!(root.fields[0].op, colbin::plan::OP_INT64S);
    assert_eq!(root.fields[1].op, OP_STRINGS);
    assert_eq!(root.fields[2].op, OP_STRUCTS);
    assert_eq!(root.fields[2].sub, Some(1));
    assert_eq!(
        inferred.schema.plan(1).expect("rows").fields[0].op,
        OP_INT64
    );
}

/// The refusals `js/tests/documents.mjs` lists: shapes the encoder must reject
/// rather than encode badly. The message is checked, not only the refusal — a
/// caller acts on what it says.
#[test]
fn the_shapes_the_format_has_no_room_for_are_refused() {
    let cases: [(&str, &str, i32); 7] = [
        ("type-conflict", r#"[{"qty":1},{"qty":"two"}]"#, D_CONFLICT),
        ("empty-array", "[]", D_CONFLICT),
        ("null-root", "null", D_CONFLICT),
        ("float-array", r#"{"v":[1.5,2.5]}"#, D_UNSUPPORTED),
        ("bool-array", r#"{"v":[true,false]}"#, D_UNSUPPORTED),
        ("nested-array", r#"{"v":[[1,2]]}"#, D_UNSUPPORTED),
        (
            "int-spanning-both-ends",
            r#"[{"v":-1},{"v":18446744073709551615}]"#,
            D_CONFLICT,
        ),
    ];
    let wanted: [&str; 7] = [
        "type conflict",
        "no shape to infer",
        "no shape to infer",
        "array of floats",
        "array of booleans",
        "array of arrays",
        "below zero and above the int64 maximum",
    ];

    for ((name, text, code), want) in cases.into_iter().zip(wanted) {
        let diag = schema_of(text).expect_err(name);
        assert_eq!(diag.code, code, "{name}: {}", diag.message);
        assert!(
            diag.message.contains(want),
            "{name}: wanted {want:?}, got {:?}",
            diag.message,
        );
    }
}

/// And the ones that are encodable but lossy: a warning rather than a refusal,
/// so the caller is told what the schema decided for them.
#[test]
fn the_guesses_the_encoder_has_to_make_are_warned_about() {
    let cases: [(&str, &str); 3] = [
        (r#"{"v":null}"#, "only ever null"),
        (r#"{"v":[]}"#, "always an empty array"),
        (r#"{"v":[null,null]}"#, "only nulls"),
    ];
    for (text, want) in cases {
        let mut diag = Diag::new();
        let doc = parse::parse(text.as_bytes(), &mut diag).expect("parse");
        infer::infer(&doc, &mut diag).expect("infer");
        assert!(
            diag.warnings.iter().any(|w| w.contains(want)),
            "{text}: wanted a warning about {want:?}, got {:?}",
            diag.warnings,
        );
    }
}
