// Code generated by colbin. DO NOT EDIT.
// Regenerate: COLBIN_UPDATE=1 go test ./codec -run TestGeneratedCodecIsUpToDate

package codec

import (
	"errors"

	"github.com/ivanjoz/colbin/wire"
)

// GenCharge and GenWide are the records the methods below are generated for.
// The types live beside their generated code so TestGeneratedCodecIsUpToDate can
// regenerate and compare, which is what stops the two drifting.
type GenCharge struct {
	CompanyID    int32  `cb:"1"`
	UserID       int32  `cb:"2"`
	RouteID      uint16 `cb:"3"`
	CPU          uint16 `cb:"4"`
	Inference    uint16 `cb:"5"`
	ExtraAllowed bool   `cb:"6"`
	Access1      uint16 `cb:"7"`
	Access2      uint16 `cb:"8"`
	Access3      uint16 `cb:"9"`
	Access4      uint16 `cb:"10"`
}

// GenWide takes eight-bit keys, and the conversions the generator emits: a
// named type, a platform-width integer, and every variable-length value.
type GenWide struct {
	ID     int       `cb:"1"`
	Status genStatus `cb:"2"`
	Name   string    `cb:"3"`
	Blob   []byte    `cb:"4"`
	Scores []int32   `cb:"5"`
	Tags   []string  `cb:"6"`
	Ratio  float64   `cb:"7"`
	Small  int8      `cb:"8"`
	Big    uint64    `cb:"40"`
}

type genStatus uint8

// AppendColbin encodes v onto dst.
func (v *GenCharge) AppendColbin(dst []byte) []byte {
	w := wire.Writer{Buffer: append(dst, 0xd0)}
	w.I32(0, v.CompanyID)
	w.I32(1, v.UserID)
	w.U16(2, v.RouteID)
	w.U16(3, v.CPU)
	w.U16(4, v.Inference)
	w.Bool(5, v.ExtraAllowed)
	w.U16(6, v.Access1)
	w.U16(7, v.Access2)
	w.U16(8, v.Access3)
	w.U16(9, v.Access4)
	return w.Buffer
}

// UnmarshalColbin decodes a colbin message into v, zeroing it first:
// a key the message omits means the field was zero.
func (v *GenCharge) UnmarshalColbin(data []byte) error {
	if len(data) == 0 {
		return errors.New("colbin: an empty GenCharge message")
	}
	switch data[0] {
	case 0xd0:
		data = data[1:]
	case 0xd4:
		// A self-describing message: the schema section is stepped over.
		length, width, ok := wire.ReadLength(data[1:])
		if !ok || length > len(data)-1-width {
			return errors.New("colbin: a GenCharge message's schema section is truncated")
		}
		data = data[1+width+length:]
	default:
		return errors.New("colbin: not a narrow-key GenCharge message")
	}
	*v = GenCharge{}
	r := wire.NewReader(data)
	for r.More() {
		switch r.Key() {
		case 0:
			v.CompanyID = r.I32()
		case 1:
			v.UserID = r.I32()
		case 2:
			v.RouteID = r.U16()
		case 3:
			v.CPU = r.U16()
		case 4:
			v.Inference = r.U16()
		case 5:
			v.ExtraAllowed = r.Bool()
		case 6:
			v.Access1 = r.U16()
		case 7:
			v.Access2 = r.U16()
		case 8:
			v.Access3 = r.U16()
		case 9:
			v.Access4 = r.U16()
		default:
			r.Skip()
		}
	}
	return r.Err()
}

// AppendColbin encodes v onto dst.
func (v *GenWide) AppendColbin(dst []byte) []byte {
	w := wire.Writer8{Buffer: append(dst, 0xd8)}
	w.Int(0, int64(v.ID))
	w.U16(1, uint16(v.Status))
	w.String(2, v.Name)
	w.Bytes(3, v.Blob)
	w.Int32s(4, v.Scores)
	w.Strings(5, v.Tags)
	w.F64(6, v.Ratio)
	w.Int(7, int64(v.Small))
	w.Uint(39, v.Big)
	return w.Buffer
}

// UnmarshalColbin decodes a colbin message into v, zeroing it first:
// a key the message omits means the field was zero.
func (v *GenWide) UnmarshalColbin(data []byte) error {
	if len(data) == 0 {
		return errors.New("colbin: an empty GenWide message")
	}
	switch data[0] {
	case 0xd8:
		data = data[1:]
	case 0xdc:
		// A self-describing message: the schema section is stepped over.
		length, width, ok := wire.ReadLength(data[1:])
		if !ok || length > len(data)-1-width {
			return errors.New("colbin: a GenWide message's schema section is truncated")
		}
		data = data[1+width+length:]
	default:
		return errors.New("colbin: not a wide-key GenWide message")
	}
	*v = GenWide{}
	r := wire.NewReader8(data)
	for r.More() {
		switch r.Key() {
		case 0:
			if x := r.Int(); int64(int(x)) == x {
				v.ID = int(x)
			} else {
				r.Fail(wire.ErrFieldTooWide)
			}
		case 1:
			v.Status = genStatus(r.U8())
		case 2:
			v.Name = r.String()
		case 3:
			v.Blob = append([]byte(nil), r.Bytes()...)
		case 4:
			v.Scores = r.Int32s(nil)
		case 5:
			v.Tags = r.Strings(nil)
		case 6:
			v.Ratio = r.F64()
		case 7:
			v.Small = r.I8()
		case 39:
			v.Big = r.Uint()
		default:
			r.Skip()
		}
	}
	return r.Err()
}
