// Code generated by colbin. DO NOT EDIT.
// Regenerate: go test ./codec -run TestGeneratedCodecIsUpToDate

package codec

import (
	"errors"

	"github.com/ivanjoz/colbin/wire"
)

// GenCharge is the record the methods below are generated for. The type lives
// beside its generated code so TestGeneratedCodecIsUpToDate can regenerate and
// compare, which is what stops the two drifting.
type GenCharge struct {
	CompanyID    int32  `cb:"1"`
	UserID       int32  `cb:"2"`
	RouteID      uint16 `cb:"3"`
	CPU          uint16 `cb:"4"`
	Inference    uint16 `cb:"5"`
	ExtraAllowed bool   `cb:"6"`
	Access1      uint16 `cb:"7"`
	Access2      uint16 `cb:"8"`
	Access3      uint16 `cb:"9"`
	Access4      uint16 `cb:"10"`
}

// Generated for GenCharge. Keys 0..9.
const _ = uint(15 - 9) // fails to build if a key exceeds the width

// AppendColbin encodes v onto dst in colbin's the format.
func (v *GenCharge) AppendColbin(dst []byte) []byte {
	w := wire.Writer{Buffer: append(dst, 0xd0)}
	w.I32(0, v.CompanyID)
	w.I32(1, v.UserID)
	w.U16(2, v.RouteID)
	w.U16(3, v.CPU)
	w.U16(4, v.Inference)
	w.Bool(5, v.ExtraAllowed)
	w.U16(6, v.Access1)
	w.U16(7, v.Access2)
	w.U16(8, v.Access3)
	w.U16(9, v.Access4)
	return w.Buffer
}

// UnmarshalColbin decodes a colbin message into v, zeroing it first:
// a key the message omits means the field was zero.
func (v *GenCharge) UnmarshalColbin(data []byte) error {
	*v = GenCharge{}
	if len(data) == 0 || data[0] != 0xd0 {
		return errors.New("colbin: not a narrow-key GenCharge message")
	}
	r := wire.NewReader(data[1:])
	for r.More() {
		switch r.Key() {
		case 0:
			v.CompanyID = r.I32()
		case 1:
			v.UserID = r.I32()
		case 2:
			v.RouteID = r.U16()
		case 3:
			v.CPU = r.U16()
		case 4:
			v.Inference = r.U16()
		case 5:
			v.ExtraAllowed = r.Bool()
		case 6:
			v.Access1 = r.U16()
		case 7:
			v.Access2 = r.U16()
		case 8:
			v.Access3 = r.U16()
		case 9:
			v.Access4 = r.U16()
		default:
			r.Skip()
		}
	}
	return r.Err()
}
