package codec

// A source generator for the format.
//
// The plan walk in wire.go resolves a type once and then switches over that
// plan per field, which costs 22 ns to encode a ten-field record where the
// straight-line calls it is standing in for cost 5.1. The difference is not the
// reflection — that happens once — it is the switch, the offsets loaded from the
// plan, and the unsafe.Add per field, none of which the compiler can fold
// because none of them is a constant.
//
// A generator turns them all into constants. It emits exactly what a hand-written
// codec would write, so the generated encode is the 5.1 ns row of the table in
// wire/README.md rather than the 22 ns one — and the decode is a switch over
// a constant key, which Go compiles to a jump table.
//
// It works from a reflect.Type rather than by parsing source, so it reuses the
// same plan builder the reflective path uses and cannot disagree with it about
// field ids, types or which fields are encodable. The cost is that the caller
// writes a three-line generator program; the benefit is that there is one
// definition of what a plan is.

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"reflect"
	"strings"
)

// opCalls maps a plan op to the writer call and reader expression that
// implement it, with %s standing for the field selector.
//
// The writer entry picks the width-typed method that matches the field's Go
// type, which is the whole point: a uint16 field must reach U16 and not Uint,
// because Uint carries every width the format has and does not inline.
var opCalls = map[fieldOp]struct{ write, read string }{
	opBool:    {"w.Bool(%d, v.%s)", "r.Bool()"},
	opInt8:    {"w.Int(%d, int64(v.%s))", "int8(r.Int())"},
	opInt16:   {"w.Int(%d, int64(v.%s))", "int16(r.Int())"},
	opInt32:   {"w.I32(%d, v.%s)", "r.I32()"},
	opInt64:   {"w.Int(%d, v.%s)", "r.Int()"},
	opUint8:   {"w.U16(%d, uint16(v.%s))", "uint8(r.U16())"},
	opUint16:  {"w.U16(%d, v.%s)", "r.U16()"},
	opUint32:  {"w.U32(%d, v.%s)", "r.U32()"},
	opUint64:  {"w.Uint(%d, v.%s)", "r.Uint()"},
	opFloat32: {"w.F32(%d, v.%s)", "r.F32()"},
	opFloat64: {"w.F64(%d, v.%s)", "r.F64()"},
	opString:  {"w.String(%d, v.%s)", "r.String()"},
	opBytes:   {"w.Bytes(%d, v.%s)", "append([]byte(nil), r.Bytes()...)"},
	opInt8s:   {"w.Int8s(%d, v.%s)", "r.Int8s(nil)"},
	opInt16s:  {"w.Int16s(%d, v.%s)", "r.Int16s(nil)"},
	opInt32s:  {"w.Int32s(%d, v.%s)", "r.Int32s(nil)"},
	opInt64s:  {"w.Ints(%d, v.%s)", "r.Ints(nil)"},
	opUint16s: {"w.Uint16s(%d, v.%s)", "r.Uint16s(nil)"},
	opUint32s: {"w.Uint32s(%d, v.%s)", "r.Uint32s(nil)"},
	opUint64s: {"w.Uint64s(%d, v.%s)", "r.Uint64s(nil)"},
	opStrings: {"w.Strings(%d, v.%s)", "r.Strings(nil)"},
}

// Generate writes Go source implementing AppendColbin and UnmarshalColbin
// for every value in types, into package pkg.
//
// Each value is used only for its type, so the zero value is the usual argument:
//
//	func main() {
//	    var out bytes.Buffer
//	    codec.Generate(&out, "billing", Charge{}, Invoice{})
//	    os.WriteFile("colbin_gen.go", out.Bytes(), 0o644)
//	}
func Generate(out io.Writer, pkg string, types ...any) error {
	var body bytes.Buffer
	fmt.Fprintf(&body, "// Code generated by colbin. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	fmt.Fprintf(&body, "import (\n\t%q\n\n\t%q\n)\n\n", "errors", "github.com/ivanjoz/colbin/wire")

	for _, value := range types {
		structType := reflect.TypeOf(value)
		for structType != nil && structType.Kind() == reflect.Pointer {
			structType = structType.Elem()
		}
		if structType == nil {
			return fmt.Errorf("colbin: Generate needs a struct, got nil")
		}
		if err := generateOne(&body, structType); err != nil {
			return err
		}
	}

	// gofmt the result rather than getting the whitespace right by hand: the
	// generator's job is to be correct, not to be a pretty-printer.
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return fmt.Errorf("colbin: generated source does not parse: %w\n%s", err, body.String())
	}
	_, err = out.Write(formatted)
	return err
}

func generateOne(out *bytes.Buffer, structType reflect.Type) error {
	plan, err := planFor(structType)
	if err != nil {
		return err
	}
	if plan.wide() {
		return fmt.Errorf(
			"colbin: %s needs eight-bit keys, which the generator does not emit yet",
			structType)
	}
	name := structType.Name()
	if name == "" {
		return fmt.Errorf("colbin: Generate needs a named struct, got %s", structType)
	}

	// The field names in declaration order, which is the order the plan holds.
	names := make([]string, 0, len(plan.fields))
	for index := range structType.NumField() {
		field := structType.Field(index)
		if !field.IsExported() {
			continue
		}
		if _, _, skip := parseCbTag(field); skip {
			continue
		}
		names = append(names, field.Name)
	}
	if len(names) != len(plan.fields) {
		return fmt.Errorf("colbin: %s: %d plan fields for %d names", name, len(plan.fields), len(names))
	}

	// The compile-time key assertion the writer's doc comment prescribes. It
	// costs nothing at run time and fails the build if a tag is edited past the
	// key width, which is the check the writer deliberately does not make.
	var highest uint8
	for _, field := range plan.fields {
		highest = max(highest, field.key)
	}
	fmt.Fprintf(out, "// Generated for %s. Keys 0..%d.\n", name, highest)
	fmt.Fprintf(out, "const _ = uint(%d - %d) // fails to build if a key exceeds the width\n\n",
		maxNarrowKey, highest)

	fmt.Fprintf(out, "// AppendColbin encodes v onto dst in colbin's the format.\n")
	fmt.Fprintf(out, "func (v *%s) AppendColbin(dst []byte) []byte {\n", name)
	// The root descriptor, which is what makes the generated bytes identical to
	// the reflective ones rather than merely equivalent.
	fmt.Fprintf(out, "\tw := wire.Writer{Buffer: append(dst, %#02x)}\n", rootStructNarrow)
	for index, field := range plan.fields {
		calls, ok := opCalls[field.op]
		if !ok {
			return fmt.Errorf("colbin: %s.%s: no generated form for this type", name, names[index])
		}
		fmt.Fprintf(out, "\t"+calls.write+"\n", field.key, names[index])
	}
	fmt.Fprintf(out, "\treturn w.Buffer\n}\n\n")

	fmt.Fprintf(out, "// UnmarshalColbin decodes a colbin message into v, zeroing it first:\n")
	fmt.Fprintf(out, "// a key the message omits means the field was zero.\n")
	fmt.Fprintf(out, "func (v *%s) UnmarshalColbin(data []byte) error {\n", name)
	fmt.Fprintf(out, "\t*v = %s{}\n", name)
	fmt.Fprintf(out, "\tif len(data) == 0 || data[0] != %#02x {\n", rootStructNarrow)
	fmt.Fprintf(out, "\t\treturn errors.New(\"colbin: not a narrow-key %s message\")\n\t}\n", name)
	fmt.Fprintf(out, "\tr := wire.NewReader(data[1:])\n")
	fmt.Fprintf(out, "\tfor r.More() {\n\t\tswitch r.Key() {\n")
	for index, field := range plan.fields {
		calls := opCalls[field.op]
		fmt.Fprintf(out, "\t\tcase %d:\n\t\t\tv.%s = %s\n", field.key, names[index], calls.read)
	}
	fmt.Fprintf(out, "\t\tdefault:\n\t\t\tr.Skip()\n\t\t}\n\t}\n")
	fmt.Fprintf(out, "\treturn r.Err()\n}\n\n")
	return nil
}

// maxNarrowKey is the largest key the narrow width carries, named here so the
// generated assertion reads as a bound rather than a magic number.
const maxNarrowKey = 15

// GenerateString is Generate into a string, for a test or a quick
// look at what a type will produce.
func GenerateString(pkg string, types ...any) (string, error) {
	var out strings.Builder
	if err := Generate(&out, pkg, types...); err != nil {
		return "", err
	}
	return out.String(), nil
}
