package codec

import (
	"bytes"
	"go/format"
	"os"
	"reflect"
	"strconv"
	"strings"
	"testing"

	"github.com/ivanjoz/colbin/wire"
)

func TestGenerateMinimalProducesCompilableSource(t *testing.T) {
	source, err := GenerateString("billing", benchRecord{})
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		"func (v *benchRecord) AppendColbin(dst []byte) []byte",
		"w.I32(0, v.CompanyID)",
		"w.U16(2, v.RouteID)",
		"w.Bool(5, v.ExtraAllowed)",
		"case 6:",
		"v.Access1 = r.U16()",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source is missing %q:\n%s", want, source)
		}
	}
}

// A field the generated code cannot convert is named, rather than generating
// source that does not build.
func TestGenerateRefusesWhatItCannotSpell(t *testing.T) {
	type nested struct {
		Inner charge `cb:"1"`
	}
	type ints struct {
		Counts []int `cb:"1"`
	}
	type statuses struct {
		All []genStatus `cb:"1"`
	}
	for _, value := range []any{nested{}, ints{}, statuses{}} {
		if _, err := GenerateString("codec", value); err == nil {
			t.Fatalf("%T was generated", value)
		}
	}
}

// genChargeTypes is the part of gencharge_colbin_test.go the generator does not
// write: the types it is generated for.
const genChargeTypes = `
// GenCharge and GenWide are the records the methods below are generated for.
// The types live beside their generated code so TestGeneratedCodecIsUpToDate can
// regenerate and compare, which is what stops the two drifting.
type GenCharge struct {
	CompanyID    int32  ` + "`cb:\"1\"`" + `
	UserID       int32  ` + "`cb:\"2\"`" + `
	RouteID      uint16 ` + "`cb:\"3\"`" + `
	CPU          uint16 ` + "`cb:\"4\"`" + `
	Inference    uint16 ` + "`cb:\"5\"`" + `
	ExtraAllowed bool   ` + "`cb:\"6\"`" + `
	Access1      uint16 ` + "`cb:\"7\"`" + `
	Access2      uint16 ` + "`cb:\"8\"`" + `
	Access3      uint16 ` + "`cb:\"9\"`" + `
	Access4      uint16 ` + "`cb:\"10\"`" + `
}

// GenWide takes eight-bit keys, and the conversions the generator emits: a
// named type, a platform-width integer, and every variable-length value.
type GenWide struct {
	ID     int       ` + "`cb:\"1\"`" + `
	Status genStatus ` + "`cb:\"2\"`" + `
	Name   string    ` + "`cb:\"3\"`" + `
	Blob   []byte    ` + "`cb:\"4\"`" + `
	Scores []int32   ` + "`cb:\"5\"`" + `
	Tags   []string  ` + "`cb:\"6\"`" + `
	Ratio  float64   ` + "`cb:\"7\"`" + `
	Small  int8      ` + "`cb:\"8\"`" + `
	Big    uint64    ` + "`cb:\"40\"`" + `
}

type genStatus uint8
`

// renderGenCharge is the whole of gencharge_colbin_test.go: the generator's
// output with the types inserted after its imports.
func renderGenCharge() ([]byte, error) {
	source, err := GenerateString("codec", GenCharge{}, GenWide{})
	if err != nil {
		return nil, err
	}
	header := "// Code generated by colbin. DO NOT EDIT.\n"
	source = strings.Replace(source, header,
		header+"// Regenerate: COLBIN_UPDATE=1 go test ./codec -run TestGeneratedCodecIsUpToDate\n", 1)
	imports := "\"github.com/ivanjoz/colbin/wire\"\n)\n"
	source = strings.Replace(source, imports, imports+genChargeTypes, 1)
	return format.Source([]byte(source))
}

// The checked-in generated codec must match what the generator produces now, so
// that a change to the format or to the plan cannot leave stale generated code
// compiling against it.
func TestGeneratedCodecIsUpToDate(t *testing.T) {
	want, err := renderGenCharge()
	if err != nil {
		t.Fatal(err)
	}
	have, _ := os.ReadFile("gencharge_colbin_test.go")
	if bytes.Equal(have, want) {
		return
	}
	if os.Getenv("COLBIN_UPDATE") != "" {
		if err := os.WriteFile("gencharge_colbin_test.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatal("gencharge_colbin_test.go is stale: COLBIN_UPDATE=1 go test ./codec -run TestGeneratedCodecIsUpToDate")
}

// The generated codec must agree with the reflective one byte for byte, and
// round-trip through it. Nothing else guarantees the generator emits the same
// width-typed call the plan walk would take.
func TestGeneratedCodecMatchesReflection(t *testing.T) {
	charge := GenCharge{CompanyID: 7, UserID: 42, RouteID: 103, CPU: 5, Access1: 0x0139}
	checkGenerated(t, &charge, charge.AppendColbin, (*GenCharge).UnmarshalColbin)

	wide := GenWide{ID: -1 << 30, Status: 3, Name: "wide", Blob: []byte{0, 1},
		Scores: []int32{-1, 2}, Tags: []string{"a", ""}, Ratio: 0.5, Small: -8, Big: 1 << 63}
	checkGenerated(t, &wide, wide.AppendColbin, (*GenWide).UnmarshalColbin)
}

func checkGenerated[T any](t *testing.T, value *T, appendColbin func([]byte) []byte, unmarshal func(*T, []byte) error) {
	t.Helper()
	generated := appendColbin(nil)
	reflected, err := Append(nil, value)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(generated, reflected) {
		t.Fatalf("%T: generated %x, reflective %x", value, generated, reflected)
	}

	var back T
	if err := unmarshal(&back, generated); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(&back, value) {
		t.Fatalf("round-tripped as %+v", back)
	}
	// The reflective decoder reads what the generated encoder wrote.
	back = *new(T)
	if err := Unmarshal(generated, &back); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(&back, value) {
		t.Fatalf("reflective decode gave %+v", back)
	}
	// And the generated decoder steps over a schema section.
	described, err := MarshalSelfDescribing(value)
	if err != nil {
		t.Fatal(err)
	}
	back = *new(T)
	if err := unmarshal(&back, described); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(&back, value) {
		t.Fatalf("a self-describing message decoded as %+v", back)
	}
	// A truncated message is an error, not a shorter record.
	if err := unmarshal(&back, generated[:len(generated)-1]); err == nil {
		t.Fatalf("%T: a truncated message decoded", value)
	}
}

// A platform-width int is written at 64 bits and read back range-checked, so a
// 32-bit build refuses a value it cannot hold — as the reflective decoder does —
// and a 64-bit one takes it.
func TestGeneratedIntIsRangeChecked(t *testing.T) {
	writer := wire.Writer8{Buffer: []byte{rootStructWide}}
	writer.Int(0, 1<<40)
	var generated GenWide
	generatedErr := generated.UnmarshalColbin(writer.Buffer)
	var reflected GenWide
	reflectedErr := Unmarshal(writer.Buffer, &reflected)
	if strconv.IntSize == 64 {
		if generatedErr != nil || int64(generated.ID) != 1<<40 {
			t.Fatalf("a 64-bit int read as %d, %v", generated.ID, generatedErr)
		}
		return
	}
	if generatedErr == nil || reflectedErr == nil {
		t.Fatalf("2^40 was read into a 32-bit int: generated %v, reflective %v",
			generatedErr, reflectedErr)
	}
}

// An unknown narrow key ends a generated decode, as it does a reflective one: it
// cannot be stepped over.
func TestGeneratedNarrowDecodeRefusesAnUnknownKey(t *testing.T) {
	message, err := Marshal(&everyShape{Counts: []uint32{7}})
	if err != nil {
		t.Fatal(err)
	}
	var back GenCharge
	if err := back.UnmarshalColbin(message); err == nil {
		t.Fatal("a foreign key was decoded")
	}
}

var genCharge = GenCharge{CompanyID: 7, UserID: 42, RouteID: 103, CPU: 5, Access1: 0x0139}

func BenchmarkGeneratedAppend(b *testing.B) {
	buffer := make([]byte, 0, 64)
	b.ReportAllocs()
	for b.Loop() {
		buffer = genCharge.AppendColbin(buffer[:0])
	}
}

func BenchmarkGeneratedUnmarshal(b *testing.B) {
	message := genCharge.AppendColbin(nil)
	var back GenCharge
	b.ReportAllocs()
	for b.Loop() {
		_ = back.UnmarshalColbin(message)
	}
}
