package codec

// A source generator for the format.
//
// The plan walk resolves a type once and then switches over that plan per
// field. The switch, the offsets loaded from the plan and the unsafe.Add per
// field are what a generated codec turns into constants: it emits the
// straight-line calls a hand-written codec would, and its decode is a switch over
// a constant key, which Go compiles to a jump table.
//
// It works from a reflect.Type rather than by parsing source, so it reuses the
// same plan builder the reflective path uses, and the calls it emits come from
// the same table the reflective walks are generated from (ops.go). It cannot
// disagree with them about field ids, types or which fields are encodable.

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"reflect"
	"strings"
)

// Generate writes Go source implementing AppendColbin and UnmarshalColbin
// for every value in types, into package pkg.
//
// Each value is used only for its type, so the zero value is the usual argument:
//
//	func main() {
//	    var out bytes.Buffer
//	    codec.Generate(&out, "billing", Charge{}, Invoice{})
//	    os.WriteFile("colbin_gen.go", out.Bytes(), 0o644)
//	}
//
// A type qualifies when every field is a scalar, a string, a []byte or a slice
// of integers or strings — what the flat walk carries — at either key width.
// A field of a named type is converted to and from the type its op reads; a
// slice of a named element type cannot be, and is refused.
//
// The generated encoder writes strings raw: packed5 is a setting of the
// reflective encoder. The generated decoder reads either form, and steps over a
// schema section in front of the message.
func Generate(out io.Writer, pkg string, types ...any) error {
	var body bytes.Buffer
	fmt.Fprintf(&body, "// Code generated by colbin. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	fmt.Fprintf(&body, "import (\n\t%q\n\n\t%q\n)\n\n", "errors", "github.com/ivanjoz/colbin/wire")

	for _, value := range types {
		structType := reflect.TypeOf(value)
		for structType != nil && structType.Kind() == reflect.Pointer {
			structType = structType.Elem()
		}
		if structType == nil {
			return fmt.Errorf("colbin: Generate needs a struct, got nil")
		}
		if err := generateOne(&body, structType); err != nil {
			return err
		}
	}

	// gofmt the result rather than getting the whitespace right by hand: the
	// generator's job is to be correct, not to be a pretty-printer.
	formatted, err := format.Source(body.Bytes())
	if err != nil {
		return fmt.Errorf("colbin: generated source does not parse: %w\n%s", err, body.String())
	}
	_, err = out.Write(formatted)
	return err
}

func generateOne(out *bytes.Buffer, structType reflect.Type) error {
	plan, err := planFor(structType)
	if err != nil {
		return err
	}
	name := structType.Name()
	if name == "" {
		return fmt.Errorf("colbin: Generate needs a named struct, got %s", structType)
	}
	if plan.ids != nil {
		return fmt.Errorf(
			"colbin: Generate: %s numbers fields past %d, which puts it on pages, "+
				"and the generated code writes one key run: use Codec[T]", name, pageFields)
	}
	names := plan.goNames(structType)
	writes := make([]string, len(plan.fields))
	reads := make([]string, len(plan.fields))
	for index, field := range plan.fields {
		goField, _ := structType.FieldByName(names[index])
		writes[index], reads[index], err = generatedCalls(field, goField.Type, names[index], structType.PkgPath())
		if err != nil {
			return fmt.Errorf("colbin: Generate: %s.%s: %w", name, names[index], err)
		}
	}

	writer, newReader, root, schemaRoot, width := "wire.Writer", "wire.NewReader",
		rootStructNarrow, rootStructNarrowSchema, "narrow"
	if plan.isWide {
		writer, newReader, root, schemaRoot, width = "wire.Writer8", "wire.NewReader8",
			rootStructWide, rootStructWideSchema, "wide"
	}

	fmt.Fprintf(out, "// AppendColbin encodes v onto dst.\n")
	fmt.Fprintf(out, "func (v *%s) AppendColbin(dst []byte) []byte {\n", name)
	// The root descriptor, which is what makes the generated bytes identical to
	// the reflective ones rather than merely equivalent.
	fmt.Fprintf(out, "\tw := %s{Buffer: append(dst, %#02x)}\n", writer, root)
	for _, write := range writes {
		fmt.Fprintf(out, "\t%s\n", write)
	}
	fmt.Fprintf(out, "\treturn w.Buffer\n}\n\n")

	fmt.Fprintf(out, "// UnmarshalColbin decodes a colbin message into v, zeroing it first:\n")
	fmt.Fprintf(out, "// a key the message omits means the field was zero.\n")
	fmt.Fprintf(out, "func (v *%s) UnmarshalColbin(data []byte) error {\n", name)
	fmt.Fprintf(out, "\tif len(data) == 0 {\n\t\treturn errors.New(\"colbin: an empty %s message\")\n\t}\n", name)
	fmt.Fprintf(out, "\tswitch data[0] {\n\tcase %#02x:\n\t\tdata = data[1:]\n", root)
	fmt.Fprintf(out, "\tcase %#02x:\n", schemaRoot)
	fmt.Fprintf(out, "\t\t// A self-describing message: the schema section is stepped over.\n")
	fmt.Fprintf(out, "\t\tlength, width, ok := wire.ReadLength(data[1:])\n")
	fmt.Fprintf(out, "\t\tif !ok || length > len(data)-1-width {\n")
	fmt.Fprintf(out, "\t\t\treturn errors.New(\"colbin: a %s message's schema section is truncated\")\n\t\t}\n", name)
	fmt.Fprintf(out, "\t\tdata = data[1+width+length:]\n")
	fmt.Fprintf(out, "\tdefault:\n\t\treturn errors.New(\"colbin: not a %s-key %s message\")\n\t}\n", width, name)
	fmt.Fprintf(out, "\t*v = %s{}\n", name)
	fmt.Fprintf(out, "\tr := %s(data)\n", newReader)
	fmt.Fprintf(out, "\tfor r.More() {\n\t\tswitch r.Key() {\n")
	for index, field := range plan.fields {
		fmt.Fprintf(out, "\t\tcase %d:\n\t\t\t%s\n", field.key, reads[index])
	}
	// An unknown key is stepped over at either width.
	fmt.Fprintf(out, "\t\tdefault:\n\t\t\tr.Skip()\n\t\t}\n\t}\n")
	fmt.Fprintf(out, "\treturn r.Err()\n}\n\n")
	return nil
}

// generatedCalls is one field's write statement and read statement, from its
// row of valueOps, converting a field of another type to and from the one the
// row reads.
//
// A platform-width integer is generated at 64 bits, so the source is the same
// whichever platform ran the generator, and its read is range-checked, so a
// 32-bit build refuses a value it cannot hold rather than truncating it.
func generatedCalls(field planField, fieldType reflect.Type, name, pkgPath string) (write, read string, err error) {
	row, ok := valueOpOf(schemaOp(field.op, field.native))
	if !ok || field.indirect {
		return "", "", fmt.Errorf("a %s field has no generated form: Generate emits flat records", fieldType)
	}
	same := fieldType == row.goType
	if !same && (!fieldType.ConvertibleTo(row.goType) || !row.goType.ConvertibleTo(fieldType)) {
		return "", "", fmt.Errorf("a %s does not convert to the %s its op reads", fieldType, goTypeName(row))
	}
	value := "v." + name
	switch {
	case row.widen != "":
		value = row.widen + "(" + value + ")"
	case !same:
		value = goTypeName(row) + "(" + value + ")"
	}
	write = fmt.Sprintf("w.%s(%d, %s)", row.write, field.key, value)
	read = "r." + row.read
	if row.op == opBytes {
		read = "append([]byte(nil), " + read + "...)"
	}
	if same {
		return write, fmt.Sprintf("v.%s = %s", name, read), nil
	}
	local, err := localTypeName(fieldType, pkgPath)
	if err != nil {
		return "", "", err
	}
	if field.native {
		return write, fmt.Sprintf(
			"if x := %s; %s(%s(x)) == x {\n\tv.%s = %s(x)\n} else {\n\tr.Fail(wire.ErrFieldTooWide)\n}",
			read, goTypeName(row), local, name, local), nil
	}
	return write, fmt.Sprintf("v.%s = %s(%s)", name, local, read), nil
}

// localTypeName spells a field's type from inside the generated file's package.
func localTypeName(fieldType reflect.Type, pkgPath string) (string, error) {
	switch fieldType.PkgPath() {
	case "":
		return fieldType.String(), nil
	case pkgPath:
		return fieldType.Name(), nil
	}
	return "", fmt.Errorf("a %s is from another package, which the generated file does not import", fieldType)
}

// GenerateString is Generate into a string, for a test or a quick
// look at what a type will produce.
func GenerateString(pkg string, types ...any) (string, error) {
	var out strings.Builder
	if err := Generate(&out, pkg, types...); err != nil {
		return "", err
	}
	return out.String(), nil
}
