package codec

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"testing"
)

// ops_gen.go is every per-field switch over a value op, rendered from valueOps.
// This test is its generator: it fails while the file on disk differs from what
// the table renders to, and rewrites it when COLBIN_UPDATE is set.
func TestValueOpsAreGenerated(t *testing.T) {
	want, err := renderValueOps()
	if err != nil {
		t.Fatal(err)
	}
	have, _ := os.ReadFile("ops_gen.go")
	if bytes.Equal(have, want) {
		return
	}
	if os.Getenv("COLBIN_UPDATE") != "" {
		if err := os.WriteFile("ops_gen.go", want, 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	t.Fatal("ops_gen.go is stale: COLBIN_UPDATE=1 go test ./codec -run TestValueOpsAreGenerated")
}

// Every value op has a row, and only value ops do: a row missing from the table
// is an op every generated switch falls through on.
func TestValueOpsCoverEveryValueOp(t *testing.T) {
	seen := map[fieldOp]bool{}
	for _, row := range valueOps {
		if seen[row.op] {
			t.Fatalf("op %d has two rows", row.op)
		}
		seen[row.op] = true
	}
	for op := fieldOp(0); op < opCount; op++ {
		_, composite := map[fieldOp]bool{
			opStruct: true, opStructs: true, opMap: true, opPointer: true,
			opPointerStruct: true, opAny: true, opAnys: true,
		}[op]
		if seen[op] == composite {
			t.Fatalf("op %d: in the table %v, composite %v", op, seen[op], composite)
		}
	}
}

func renderValueOps() ([]byte, error) {
	var out bytes.Buffer
	out.WriteString(`// Code generated by TestValueOpsAreGenerated from valueOps. DO NOT EDIT.
// Regenerate: COLBIN_UPDATE=1 go test ./codec -run TestValueOpsAreGenerated

package codec

import (
	"unsafe"

	"github.com/ivanjoz/colbin/wire"
)
`)
	for _, width := range []struct{ suffix, writer, reader string }{
		{"", "wire.Writer", "wire.Reader"},
		{"Wide", "wire.Writer8", "wire.Reader8"},
	} {
		// The flat walks: a simple plan holds value ops and nothing else, so the
		// switch needs no default.
		fmt.Fprintf(&out, "\n// appendScalars%s writes a simple plan. See scalars.go.\n", width.suffix)
		fmt.Fprintf(&out, "func appendScalars%s(writer *%s, plan *typePlan, record unsafe.Pointer) {\n", width.suffix, width.writer)
		out.WriteString("packed := Packed5()\nfor index := range plan.fields {\nfield := &plan.fields[index]\nat := unsafe.Add(record, field.offset)\nswitch field.op {\n")
		for _, row := range valueOps {
			writeArm(&out, row, "field.key")
		}
		out.WriteString("}\n}\n}\n")

		fmt.Fprintf(&out, "\n// writeValue%s writes one value op, and reports false for an op that is not\n// one, which the caller handles.\n", width.suffix)
		fmt.Fprintf(&out, "func writeValue%s(writer *%s, key uint8, op fieldOp, at unsafe.Pointer, packed bool) bool {\nswitch op {\n", width.suffix, width.writer)
		for _, row := range valueOps {
			writeArm(&out, row, "key")
		}
		out.WriteString("default:\nreturn false\n}\nreturn true\n}\n")

		// An unknown key is stepped over at either width: the narrow nibble sizes
		// a field as the wide descriptor does.
		fmt.Fprintf(&out, "\n// readScalars%s reads a simple plan. See scalars.go.\n", width.suffix)
		fmt.Fprintf(&out, "func readScalars%s(reader *%s, plan *typePlan, record unsafe.Pointer) {\n", width.suffix, width.reader)
		out.WriteString("for reader.More() {\nfield := plan.find(reader.Key())\nif field == nil {\nif !reader.Skip() {\nreturn\n}\ncontinue\n}\nat := unsafe.Add(record, field.offset)\nswitch field.op {\n")
		for _, row := range valueOps {
			readArm(&out, row)
		}
		out.WriteString("default:\nreader.Fail(errNotValueOp(field.op))\n}\n}\n}\n")

		fmt.Fprintf(&out, "\n// readValue%s reads one value op, and reports false for an op that is not\n// one, which the caller handles.\n", width.suffix)
		fmt.Fprintf(&out, "func readValue%s(reader *%s, op fieldOp, at unsafe.Pointer) bool {\nswitch op {\n", width.suffix, width.reader)
		for _, row := range valueOps {
			readArm(&out, row)
		}
		out.WriteString("default:\nreturn false\n}\nreturn true\n}\n")

		walk := "narrowScalar"
		if width.suffix != "" {
			walk = "wideScalar"
		}
		fmt.Fprintf(&out, "\n// %s hands one value op to the walk's sink. See json.go.\n", walk)
		fmt.Fprintf(&out, "func (w *walker) %s(reader *%s, op fieldOp) {\nswitch op {\n", walk, width.reader)
		for _, row := range valueOps {
			jsonArm(&out, row)
		}
		out.WriteString("default:\nw.fail(errUnwalkableOp(op))\n}\n}\n")
	}
	return format.Source(out.Bytes())
}

func writeArm(out *bytes.Buffer, row valueOp, key string) {
	value := fmt.Sprintf("*(*%s)(at)", goTypeName(row))
	if row.widen != "" {
		value = fmt.Sprintf("%s(%s)", row.widen, value)
	}
	fmt.Fprintf(out, "case %s:\n", opName(row.op))
	if row.op == opString {
		fmt.Fprintf(out, "if packed {\nwriter.PackedString(%s, %s)\n} else {\nwriter.String(%s, %s)\n}\n",
			key, value, key, value)
		return
	}
	fmt.Fprintf(out, "writer.%s(%s, %s)\n", row.write, key, value)
}

func readArm(out *bytes.Buffer, row valueOp) {
	value := "reader." + row.read
	if row.op == opBytes {
		value = fmt.Sprintf("append([]byte(nil), %s...)", value)
	}
	fmt.Fprintf(out, "case %s:\n*(*%s)(at) = %s\n", opName(row.op), goTypeName(row), value)
}

func jsonArm(out *bytes.Buffer, row valueOp) {
	read := "reader." + row.read
	var call string
	switch row.json {
	case jsonBool:
		call = fmt.Sprintf("w.to.boolean(%s)", read)
	case jsonSigned:
		if row.goType.String() != "int64" {
			read = "int64(" + read + ")"
		}
		call = fmt.Sprintf("w.to.signed(%s)", read)
	case jsonUnsigned:
		if row.goType.String() != "uint64" {
			read = "uint64(" + read + ")"
		}
		call = fmt.Sprintf("w.to.unsigned(%s)", read)
	case jsonFloat32:
		call = fmt.Sprintf("w.floatValue(float64(%s), 32)", read)
	case jsonFloat64:
		call = fmt.Sprintf("w.floatValue(%s, 64)", read)
	case jsonText:
		call = fmt.Sprintf("w.to.text(%s)", read)
	case jsonBlob:
		call = fmt.Sprintf("w.to.blob(%s)", read)
	case jsonSignedArray:
		call = fmt.Sprintf("signedArray(w, %s)", read)
	case jsonUnsignedArray:
		call = fmt.Sprintf("unsignedArray(w, %s)", read)
	case jsonTextArray:
		// Sub-slices of the message rather than strings: the sink only appends
		// them.
		call = "w.textArray(reader.StringsBytes(nil))"
	}
	fmt.Fprintf(out, "case %s:\n%s\n", opName(row.op), call)
}

// opName is an op's constant name, for the generated source.
func opName(op fieldOp) string {
	names := map[fieldOp]string{
		opBool: "opBool", opInt8: "opInt8", opInt16: "opInt16", opInt32: "opInt32",
		opInt64: "opInt64", opUint8: "opUint8", opUint16: "opUint16", opUint32: "opUint32",
		opUint64: "opUint64", opFloat32: "opFloat32", opFloat64: "opFloat64",
		opString: "opString", opBytes: "opBytes", opInt8s: "opInt8s", opInt16s: "opInt16s",
		opInt32s: "opInt32s", opInt64s: "opInt64s", opUint16s: "opUint16s",
		opUint32s: "opUint32s", opUint64s: "opUint64s", opStrings: "opStrings",
	}
	name, ok := names[op]
	if !ok {
		panic(fmt.Sprintf("op %d has no name", op))
	}
	return name
}
