// Code generated by TestValueOpsAreGenerated from valueOps. DO NOT EDIT.
// Regenerate: COLBIN_UPDATE=1 go test ./codec -run TestValueOpsAreGenerated

package codec

import (
	"unsafe"

	"github.com/ivanjoz/colbin/wire"
)

// appendScalars writes a simple plan. See scalars.go.
func appendScalars(writer *wire.Writer, plan *typePlan, record unsafe.Pointer) {
	packed := Packed5()
	for index := range plan.fields {
		field := &plan.fields[index]
		at := unsafe.Add(record, field.offset)
		switch field.op {
		case opBool:
			writer.Bool(field.key, *(*bool)(at))
		case opInt8:
			writer.Int(field.key, int64(*(*int8)(at)))
		case opInt16:
			writer.Int(field.key, int64(*(*int16)(at)))
		case opInt32:
			writer.I32(field.key, *(*int32)(at))
		case opInt64:
			writer.Int(field.key, *(*int64)(at))
		case opUint8:
			writer.U16(field.key, uint16(*(*uint8)(at)))
		case opUint16:
			writer.U16(field.key, *(*uint16)(at))
		case opUint32:
			writer.U32(field.key, *(*uint32)(at))
		case opUint64:
			writer.Uint(field.key, *(*uint64)(at))
		case opFloat32:
			writer.F32(field.key, *(*float32)(at))
		case opFloat64:
			writer.F64(field.key, *(*float64)(at))
		case opString:
			if packed {
				writer.PackedString(field.key, *(*string)(at))
			} else {
				writer.String(field.key, *(*string)(at))
			}
		case opBytes:
			writer.Bytes(field.key, *(*[]byte)(at))
		case opInt8s:
			writer.Int8s(field.key, *(*[]int8)(at))
		case opInt16s:
			writer.Int16s(field.key, *(*[]int16)(at))
		case opInt32s:
			writer.Int32s(field.key, *(*[]int32)(at))
		case opInt64s:
			writer.Ints(field.key, *(*[]int64)(at))
		case opUint16s:
			writer.Uint16s(field.key, *(*[]uint16)(at))
		case opUint32s:
			writer.Uint32s(field.key, *(*[]uint32)(at))
		case opUint64s:
			writer.Uint64s(field.key, *(*[]uint64)(at))
		case opStrings:
			writer.Strings(field.key, *(*[]string)(at))
		}
	}
}

// writeValue writes one value op, and reports false for an op that is not
// one, which the caller handles.
func writeValue(writer *wire.Writer, key uint8, op fieldOp, at unsafe.Pointer, packed bool) bool {
	switch op {
	case opBool:
		writer.Bool(key, *(*bool)(at))
	case opInt8:
		writer.Int(key, int64(*(*int8)(at)))
	case opInt16:
		writer.Int(key, int64(*(*int16)(at)))
	case opInt32:
		writer.I32(key, *(*int32)(at))
	case opInt64:
		writer.Int(key, *(*int64)(at))
	case opUint8:
		writer.U16(key, uint16(*(*uint8)(at)))
	case opUint16:
		writer.U16(key, *(*uint16)(at))
	case opUint32:
		writer.U32(key, *(*uint32)(at))
	case opUint64:
		writer.Uint(key, *(*uint64)(at))
	case opFloat32:
		writer.F32(key, *(*float32)(at))
	case opFloat64:
		writer.F64(key, *(*float64)(at))
	case opString:
		if packed {
			writer.PackedString(key, *(*string)(at))
		} else {
			writer.String(key, *(*string)(at))
		}
	case opBytes:
		writer.Bytes(key, *(*[]byte)(at))
	case opInt8s:
		writer.Int8s(key, *(*[]int8)(at))
	case opInt16s:
		writer.Int16s(key, *(*[]int16)(at))
	case opInt32s:
		writer.Int32s(key, *(*[]int32)(at))
	case opInt64s:
		writer.Ints(key, *(*[]int64)(at))
	case opUint16s:
		writer.Uint16s(key, *(*[]uint16)(at))
	case opUint32s:
		writer.Uint32s(key, *(*[]uint32)(at))
	case opUint64s:
		writer.Uint64s(key, *(*[]uint64)(at))
	case opStrings:
		writer.Strings(key, *(*[]string)(at))
	default:
		return false
	}
	return true
}

// readScalars reads a simple plan. See scalars.go.
func readScalars(reader *wire.Reader, plan *typePlan, record unsafe.Pointer) (unknown uint8, ok bool) {
	for reader.More() {
		key := reader.Key()
		field := plan.find(key)
		if field == nil {
			return key, false
		}
		at := unsafe.Add(record, field.offset)
		switch field.op {
		case opBool:
			*(*bool)(at) = reader.Bool()
		case opInt8:
			*(*int8)(at) = reader.I8()
		case opInt16:
			*(*int16)(at) = reader.I16()
		case opInt32:
			*(*int32)(at) = reader.I32()
		case opInt64:
			*(*int64)(at) = reader.Int()
		case opUint8:
			*(*uint8)(at) = reader.U8()
		case opUint16:
			*(*uint16)(at) = reader.U16()
		case opUint32:
			*(*uint32)(at) = reader.U32()
		case opUint64:
			*(*uint64)(at) = reader.Uint()
		case opFloat32:
			*(*float32)(at) = reader.F32()
		case opFloat64:
			*(*float64)(at) = reader.F64()
		case opString:
			*(*string)(at) = reader.String()
		case opBytes:
			*(*[]byte)(at) = append([]byte(nil), reader.Bytes()...)
		case opInt8s:
			*(*[]int8)(at) = reader.Int8s(nil)
		case opInt16s:
			*(*[]int16)(at) = reader.Int16s(nil)
		case opInt32s:
			*(*[]int32)(at) = reader.Int32s(nil)
		case opInt64s:
			*(*[]int64)(at) = reader.Ints(nil)
		case opUint16s:
			*(*[]uint16)(at) = reader.Uint16s(nil)
		case opUint32s:
			*(*[]uint32)(at) = reader.Uint32s(nil)
		case opUint64s:
			*(*[]uint64)(at) = reader.Uint64s(nil)
		case opStrings:
			*(*[]string)(at) = reader.Strings(nil)
		default:
			reader.Fail(errNotValueOp(field.op))
		}
	}
	return 0, true
}

// readValue reads one value op, and reports false for an op that is not
// one, which the caller handles.
func readValue(reader *wire.Reader, op fieldOp, at unsafe.Pointer) bool {
	switch op {
	case opBool:
		*(*bool)(at) = reader.Bool()
	case opInt8:
		*(*int8)(at) = reader.I8()
	case opInt16:
		*(*int16)(at) = reader.I16()
	case opInt32:
		*(*int32)(at) = reader.I32()
	case opInt64:
		*(*int64)(at) = reader.Int()
	case opUint8:
		*(*uint8)(at) = reader.U8()
	case opUint16:
		*(*uint16)(at) = reader.U16()
	case opUint32:
		*(*uint32)(at) = reader.U32()
	case opUint64:
		*(*uint64)(at) = reader.Uint()
	case opFloat32:
		*(*float32)(at) = reader.F32()
	case opFloat64:
		*(*float64)(at) = reader.F64()
	case opString:
		*(*string)(at) = reader.String()
	case opBytes:
		*(*[]byte)(at) = append([]byte(nil), reader.Bytes()...)
	case opInt8s:
		*(*[]int8)(at) = reader.Int8s(nil)
	case opInt16s:
		*(*[]int16)(at) = reader.Int16s(nil)
	case opInt32s:
		*(*[]int32)(at) = reader.Int32s(nil)
	case opInt64s:
		*(*[]int64)(at) = reader.Ints(nil)
	case opUint16s:
		*(*[]uint16)(at) = reader.Uint16s(nil)
	case opUint32s:
		*(*[]uint32)(at) = reader.Uint32s(nil)
	case opUint64s:
		*(*[]uint64)(at) = reader.Uint64s(nil)
	case opStrings:
		*(*[]string)(at) = reader.Strings(nil)
	default:
		return false
	}
	return true
}

// narrowScalar hands one value op to the walk's sink. See json.go.
func (w *walker) narrowScalar(reader *wire.Reader, op fieldOp) {
	switch op {
	case opBool:
		w.to.boolean(reader.Bool())
	case opInt8:
		w.to.signed(int64(reader.I8()))
	case opInt16:
		w.to.signed(int64(reader.I16()))
	case opInt32:
		w.to.signed(int64(reader.I32()))
	case opInt64:
		w.to.signed(reader.Int())
	case opUint8:
		w.to.unsigned(uint64(reader.U8()))
	case opUint16:
		w.to.unsigned(uint64(reader.U16()))
	case opUint32:
		w.to.unsigned(uint64(reader.U32()))
	case opUint64:
		w.to.unsigned(reader.Uint())
	case opFloat32:
		w.floatValue(float64(reader.F32()), 32)
	case opFloat64:
		w.floatValue(reader.F64(), 64)
	case opString:
		w.to.text(reader.String())
	case opBytes:
		w.to.blob(reader.Bytes())
	case opInt8s:
		signedArray(w, reader.Int8s(nil))
	case opInt16s:
		signedArray(w, reader.Int16s(nil))
	case opInt32s:
		signedArray(w, reader.Int32s(nil))
	case opInt64s:
		signedArray(w, reader.Ints(nil))
	case opUint16s:
		unsignedArray(w, reader.Uint16s(nil))
	case opUint32s:
		unsignedArray(w, reader.Uint32s(nil))
	case opUint64s:
		unsignedArray(w, reader.Uint64s(nil))
	case opStrings:
		w.textArray(reader.StringsBytes(nil))
	default:
		w.fail(errUnwalkableOp(op))
	}
}

// appendScalarsWide writes a simple plan. See scalars.go.
func appendScalarsWide(writer *wire.Writer8, plan *typePlan, record unsafe.Pointer) {
	packed := Packed5()
	for index := range plan.fields {
		field := &plan.fields[index]
		at := unsafe.Add(record, field.offset)
		switch field.op {
		case opBool:
			writer.Bool(field.key, *(*bool)(at))
		case opInt8:
			writer.Int(field.key, int64(*(*int8)(at)))
		case opInt16:
			writer.Int(field.key, int64(*(*int16)(at)))
		case opInt32:
			writer.I32(field.key, *(*int32)(at))
		case opInt64:
			writer.Int(field.key, *(*int64)(at))
		case opUint8:
			writer.U16(field.key, uint16(*(*uint8)(at)))
		case opUint16:
			writer.U16(field.key, *(*uint16)(at))
		case opUint32:
			writer.U32(field.key, *(*uint32)(at))
		case opUint64:
			writer.Uint(field.key, *(*uint64)(at))
		case opFloat32:
			writer.F32(field.key, *(*float32)(at))
		case opFloat64:
			writer.F64(field.key, *(*float64)(at))
		case opString:
			if packed {
				writer.PackedString(field.key, *(*string)(at))
			} else {
				writer.String(field.key, *(*string)(at))
			}
		case opBytes:
			writer.Bytes(field.key, *(*[]byte)(at))
		case opInt8s:
			writer.Int8s(field.key, *(*[]int8)(at))
		case opInt16s:
			writer.Int16s(field.key, *(*[]int16)(at))
		case opInt32s:
			writer.Int32s(field.key, *(*[]int32)(at))
		case opInt64s:
			writer.Ints(field.key, *(*[]int64)(at))
		case opUint16s:
			writer.Uint16s(field.key, *(*[]uint16)(at))
		case opUint32s:
			writer.Uint32s(field.key, *(*[]uint32)(at))
		case opUint64s:
			writer.Uint64s(field.key, *(*[]uint64)(at))
		case opStrings:
			writer.Strings(field.key, *(*[]string)(at))
		}
	}
}

// writeValueWide writes one value op, and reports false for an op that is not
// one, which the caller handles.
func writeValueWide(writer *wire.Writer8, key uint8, op fieldOp, at unsafe.Pointer, packed bool) bool {
	switch op {
	case opBool:
		writer.Bool(key, *(*bool)(at))
	case opInt8:
		writer.Int(key, int64(*(*int8)(at)))
	case opInt16:
		writer.Int(key, int64(*(*int16)(at)))
	case opInt32:
		writer.I32(key, *(*int32)(at))
	case opInt64:
		writer.Int(key, *(*int64)(at))
	case opUint8:
		writer.U16(key, uint16(*(*uint8)(at)))
	case opUint16:
		writer.U16(key, *(*uint16)(at))
	case opUint32:
		writer.U32(key, *(*uint32)(at))
	case opUint64:
		writer.Uint(key, *(*uint64)(at))
	case opFloat32:
		writer.F32(key, *(*float32)(at))
	case opFloat64:
		writer.F64(key, *(*float64)(at))
	case opString:
		if packed {
			writer.PackedString(key, *(*string)(at))
		} else {
			writer.String(key, *(*string)(at))
		}
	case opBytes:
		writer.Bytes(key, *(*[]byte)(at))
	case opInt8s:
		writer.Int8s(key, *(*[]int8)(at))
	case opInt16s:
		writer.Int16s(key, *(*[]int16)(at))
	case opInt32s:
		writer.Int32s(key, *(*[]int32)(at))
	case opInt64s:
		writer.Ints(key, *(*[]int64)(at))
	case opUint16s:
		writer.Uint16s(key, *(*[]uint16)(at))
	case opUint32s:
		writer.Uint32s(key, *(*[]uint32)(at))
	case opUint64s:
		writer.Uint64s(key, *(*[]uint64)(at))
	case opStrings:
		writer.Strings(key, *(*[]string)(at))
	default:
		return false
	}
	return true
}

// readScalarsWide reads a simple plan. See scalars.go.
func readScalarsWide(reader *wire.Reader8, plan *typePlan, record unsafe.Pointer) {
	for reader.More() {
		key := reader.Key()
		field := plan.find(key)
		if field == nil {
			if !reader.Skip() {
				return
			}
			continue
		}
		at := unsafe.Add(record, field.offset)
		switch field.op {
		case opBool:
			*(*bool)(at) = reader.Bool()
		case opInt8:
			*(*int8)(at) = reader.I8()
		case opInt16:
			*(*int16)(at) = reader.I16()
		case opInt32:
			*(*int32)(at) = reader.I32()
		case opInt64:
			*(*int64)(at) = reader.Int()
		case opUint8:
			*(*uint8)(at) = reader.U8()
		case opUint16:
			*(*uint16)(at) = reader.U16()
		case opUint32:
			*(*uint32)(at) = reader.U32()
		case opUint64:
			*(*uint64)(at) = reader.Uint()
		case opFloat32:
			*(*float32)(at) = reader.F32()
		case opFloat64:
			*(*float64)(at) = reader.F64()
		case opString:
			*(*string)(at) = reader.String()
		case opBytes:
			*(*[]byte)(at) = append([]byte(nil), reader.Bytes()...)
		case opInt8s:
			*(*[]int8)(at) = reader.Int8s(nil)
		case opInt16s:
			*(*[]int16)(at) = reader.Int16s(nil)
		case opInt32s:
			*(*[]int32)(at) = reader.Int32s(nil)
		case opInt64s:
			*(*[]int64)(at) = reader.Ints(nil)
		case opUint16s:
			*(*[]uint16)(at) = reader.Uint16s(nil)
		case opUint32s:
			*(*[]uint32)(at) = reader.Uint32s(nil)
		case opUint64s:
			*(*[]uint64)(at) = reader.Uint64s(nil)
		case opStrings:
			*(*[]string)(at) = reader.Strings(nil)
		default:
			reader.Fail(errNotValueOp(field.op))
		}
	}
}

// readValueWide reads one value op, and reports false for an op that is not
// one, which the caller handles.
func readValueWide(reader *wire.Reader8, op fieldOp, at unsafe.Pointer) bool {
	switch op {
	case opBool:
		*(*bool)(at) = reader.Bool()
	case opInt8:
		*(*int8)(at) = reader.I8()
	case opInt16:
		*(*int16)(at) = reader.I16()
	case opInt32:
		*(*int32)(at) = reader.I32()
	case opInt64:
		*(*int64)(at) = reader.Int()
	case opUint8:
		*(*uint8)(at) = reader.U8()
	case opUint16:
		*(*uint16)(at) = reader.U16()
	case opUint32:
		*(*uint32)(at) = reader.U32()
	case opUint64:
		*(*uint64)(at) = reader.Uint()
	case opFloat32:
		*(*float32)(at) = reader.F32()
	case opFloat64:
		*(*float64)(at) = reader.F64()
	case opString:
		*(*string)(at) = reader.String()
	case opBytes:
		*(*[]byte)(at) = append([]byte(nil), reader.Bytes()...)
	case opInt8s:
		*(*[]int8)(at) = reader.Int8s(nil)
	case opInt16s:
		*(*[]int16)(at) = reader.Int16s(nil)
	case opInt32s:
		*(*[]int32)(at) = reader.Int32s(nil)
	case opInt64s:
		*(*[]int64)(at) = reader.Ints(nil)
	case opUint16s:
		*(*[]uint16)(at) = reader.Uint16s(nil)
	case opUint32s:
		*(*[]uint32)(at) = reader.Uint32s(nil)
	case opUint64s:
		*(*[]uint64)(at) = reader.Uint64s(nil)
	case opStrings:
		*(*[]string)(at) = reader.Strings(nil)
	default:
		return false
	}
	return true
}

// wideScalar hands one value op to the walk's sink. See json.go.
func (w *walker) wideScalar(reader *wire.Reader8, op fieldOp) {
	switch op {
	case opBool:
		w.to.boolean(reader.Bool())
	case opInt8:
		w.to.signed(int64(reader.I8()))
	case opInt16:
		w.to.signed(int64(reader.I16()))
	case opInt32:
		w.to.signed(int64(reader.I32()))
	case opInt64:
		w.to.signed(reader.Int())
	case opUint8:
		w.to.unsigned(uint64(reader.U8()))
	case opUint16:
		w.to.unsigned(uint64(reader.U16()))
	case opUint32:
		w.to.unsigned(uint64(reader.U32()))
	case opUint64:
		w.to.unsigned(reader.Uint())
	case opFloat32:
		w.floatValue(float64(reader.F32()), 32)
	case opFloat64:
		w.floatValue(reader.F64(), 64)
	case opString:
		w.to.text(reader.String())
	case opBytes:
		w.to.blob(reader.Bytes())
	case opInt8s:
		signedArray(w, reader.Int8s(nil))
	case opInt16s:
		signedArray(w, reader.Int16s(nil))
	case opInt32s:
		signedArray(w, reader.Int32s(nil))
	case opInt64s:
		signedArray(w, reader.Ints(nil))
	case opUint16s:
		unsignedArray(w, reader.Uint16s(nil))
	case opUint32s:
		unsignedArray(w, reader.Uint32s(nil))
	case opUint64s:
		unsignedArray(w, reader.Uint64s(nil))
	case opStrings:
		w.textArray(reader.StringsBytes(nil))
	default:
		w.fail(errUnwalkableOp(op))
	}
}
