// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: examples.proto

package comparison

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Latitude      float64                `protobuf:"fixed64,5,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,6,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_examples_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Address) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type Person struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	Emails        []string               `protobuf:"bytes,5,rep,name=emails,proto3" json:"emails,omitempty"`
	Address       *Address               `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	AvatarHash    []byte                 `protobuf:"bytes,7,opt,name=avatar_hash,json=avatarHash,proto3" json:"avatar_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Person) Reset() {
	*x = Person{}
	mi := &file_examples_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{1}
}

func (x *Person) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Person) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Person) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Person) GetEmails() []string {
	if x != nil {
		return x.Emails
	}
	return nil
}

func (x *Person) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Person) GetAvatarHash() []byte {
	if x != nil {
		return x.AvatarHash
	}
	return nil
}

type Company struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Industry      string                 `protobuf:"bytes,3,opt,name=industry,proto3" json:"industry,omitempty"`
	Employees     []*Person              `protobuf:"bytes,4,rep,name=employees,proto3" json:"employees,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Company) Reset() {
	*x = Company{}
	mi := &file_examples_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Company) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Company) ProtoMessage() {}

func (x *Company) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Company.ProtoReflect.Descriptor instead.
func (*Company) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{2}
}

func (x *Company) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Company) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Company) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *Company) GetEmployees() []*Person {
	if x != nil {
		return x.Employees
	}
	return nil
}

func (x *Company) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int64                  `protobuf:"zigzag64,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	Stock         uint32                 `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Categories    []string               `protobuf:"bytes,6,rep,name=categories,proto3" json:"categories,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_examples_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{3}
}

func (x *Product) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPriceCents() int64 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Product) GetStock() uint32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *Product) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *Product) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type OrderLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Product        *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Quantity       uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"zigzag64,3,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	DiscountBps    []int32                `protobuf:"zigzag32,4,rep,packed,name=discount_bps,json=discountBps,proto3" json:"discount_bps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderLine) Reset() {
	*x = OrderLine{}
	mi := &file_examples_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLine) ProtoMessage() {}

func (x *OrderLine) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLine.ProtoReflect.Descriptor instead.
func (*OrderLine) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{4}
}

func (x *OrderLine) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *OrderLine) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderLine) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *OrderLine) GetDiscountBps() []int32 {
	if x != nil {
		return x.DiscountBps
	}
	return nil
}

type Order struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Customer        *Person                `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	Lines           []*OrderLine           `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	ShippingAddress *Address               `protobuf:"bytes,4,opt,name=shipping_address,json=shippingAddress,proto3" json:"shipping_address,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedUnix     int64                  `protobuf:"varint,6,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_examples_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{5}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetCustomer() *Person {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Order) GetLines() []*OrderLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Order) GetShippingAddress() *Address {
	if x != nil {
		return x.ShippingAddress
	}
	return nil
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

type Invoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Order         *Order                 `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	SubtotalCents int64                  `protobuf:"zigzag64,3,opt,name=subtotal_cents,json=subtotalCents,proto3" json:"subtotal_cents,omitempty"`
	TaxCents      int64                  `protobuf:"zigzag64,4,opt,name=tax_cents,json=taxCents,proto3" json:"tax_cents,omitempty"`
	TotalCents    int64                  `protobuf:"zigzag64,5,opt,name=total_cents,json=totalCents,proto3" json:"total_cents,omitempty"`
	Paid          bool                   `protobuf:"varint,6,opt,name=paid,proto3" json:"paid,omitempty"`
	Notes         []string               `protobuf:"bytes,7,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invoice) Reset() {
	*x = Invoice{}
	mi := &file_examples_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invoice) ProtoMessage() {}

func (x *Invoice) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invoice.ProtoReflect.Descriptor instead.
func (*Invoice) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{6}
}

func (x *Invoice) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Invoice) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *Invoice) GetSubtotalCents() int64 {
	if x != nil {
		return x.SubtotalCents
	}
	return 0
}

func (x *Invoice) GetTaxCents() int64 {
	if x != nil {
		return x.TaxCents
	}
	return 0
}

func (x *Invoice) GetTotalCents() int64 {
	if x != nil {
		return x.TotalCents
	}
	return 0
}

func (x *Invoice) GetPaid() bool {
	if x != nil {
		return x.Paid
	}
	return false
}

func (x *Invoice) GetNotes() []string {
	if x != nil {
		return x.Notes
	}
	return nil
}

type SensorReading struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SensorId        uint64                 `protobuf:"varint,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Value           float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Unit            string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	Samples         []int32                `protobuf:"zigzag32,5,rep,packed,name=samples,proto3" json:"samples,omitempty"`
	Valid           bool                   `protobuf:"varint,6,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_examples_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{7}
}

func (x *SensorReading) GetSensorId() uint64 {
	if x != nil {
		return x.SensorId
	}
	return 0
}

func (x *SensorReading) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *SensorReading) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SensorReading) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *SensorReading) GetSamples() []int32 {
	if x != nil {
		return x.Samples
	}
	return nil
}

func (x *SensorReading) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type WeatherSample struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Station         string                 `protobuf:"bytes,1,opt,name=station,proto3" json:"station,omitempty"`
	TimestampUnix   int64                  `protobuf:"varint,2,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	TemperatureC    float32                `protobuf:"fixed32,3,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	HumidityPercent float32                `protobuf:"fixed32,4,opt,name=humidity_percent,json=humidityPercent,proto3" json:"humidity_percent,omitempty"`
	WindKph         float32                `protobuf:"fixed32,5,opt,name=wind_kph,json=windKph,proto3" json:"wind_kph,omitempty"`
	Sensors         []*SensorReading       `protobuf:"bytes,6,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WeatherSample) Reset() {
	*x = WeatherSample{}
	mi := &file_examples_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeatherSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeatherSample) ProtoMessage() {}

func (x *WeatherSample) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeatherSample.ProtoReflect.Descriptor instead.
func (*WeatherSample) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{8}
}

func (x *WeatherSample) GetStation() string {
	if x != nil {
		return x.Station
	}
	return ""
}

func (x *WeatherSample) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *WeatherSample) GetTemperatureC() float32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

func (x *WeatherSample) GetHumidityPercent() float32 {
	if x != nil {
		return x.HumidityPercent
	}
	return 0
}

func (x *WeatherSample) GetWindKph() float32 {
	if x != nil {
		return x.WindKph
	}
	return 0
}

func (x *WeatherSample) GetSensors() []*SensorReading {
	if x != nil {
		return x.Sensors
	}
	return nil
}

type GeoPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float64                `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	ElevationM    int32                  `protobuf:"zigzag32,3,opt,name=elevation_m,json=elevationM,proto3" json:"elevation_m,omitempty"`
	Label         string                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPoint) Reset() {
	*x = GeoPoint{}
	mi := &file_examples_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPoint) ProtoMessage() {}

func (x *GeoPoint) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPoint.ProtoReflect.Descriptor instead.
func (*GeoPoint) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{9}
}

func (x *GeoPoint) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GeoPoint) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GeoPoint) GetElevationM() int32 {
	if x != nil {
		return x.ElevationM
	}
	return 0
}

func (x *GeoPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type Route struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Points              []*GeoPoint            `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	SegmentDurationsSec []uint32               `protobuf:"varint,4,rep,packed,name=segment_durations_sec,json=segmentDurationsSec,proto3" json:"segment_durations_sec,omitempty"`
	Toll                bool                   `protobuf:"varint,5,opt,name=toll,proto3" json:"toll,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_examples_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{10}
}

func (x *Route) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Route) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Route) GetPoints() []*GeoPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *Route) GetSegmentDurationsSec() []uint32 {
	if x != nil {
		return x.SegmentDurationsSec
	}
	return nil
}

func (x *Route) GetToll() bool {
	if x != nil {
		return x.Toll
	}
	return false
}

type BlogPost struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Author        *Person                `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Tags          []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	PublishedUnix int64                  `protobuf:"varint,6,opt,name=published_unix,json=publishedUnix,proto3" json:"published_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlogPost) Reset() {
	*x = BlogPost{}
	mi := &file_examples_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlogPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlogPost) ProtoMessage() {}

func (x *BlogPost) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlogPost.ProtoReflect.Descriptor instead.
func (*BlogPost) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{11}
}

func (x *BlogPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlogPost) GetAuthor() *Person {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *BlogPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlogPost) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *BlogPost) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BlogPost) GetPublishedUnix() int64 {
	if x != nil {
		return x.PublishedUnix
	}
	return 0
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId        uint64                 `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	Author        *Person                `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	ReplyIds      []uint64               `protobuf:"varint,5,rep,packed,name=reply_ids,json=replyIds,proto3" json:"reply_ids,omitempty"`
	Moderated     bool                   `protobuf:"varint,6,opt,name=moderated,proto3" json:"moderated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_examples_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{12}
}

func (x *Comment) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetPostId() uint64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

func (x *Comment) GetAuthor() *Person {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetReplyIds() []uint64 {
	if x != nil {
		return x.ReplyIds
	}
	return nil
}

func (x *Comment) GetModerated() bool {
	if x != nil {
		return x.Moderated
	}
	return false
}

type UserProfile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Person            *Person                `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	Biography         string                 `protobuf:"bytes,2,opt,name=biography,proto3" json:"biography,omitempty"`
	Interests         []string               `protobuf:"bytes,3,rep,name=interests,proto3" json:"interests,omitempty"`
	Preferences       map[string]string      `protobuf:"bytes,4,rep,name=preferences,proto3" json:"preferences,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PreviousAddresses []*Address             `protobuf:"bytes,5,rep,name=previous_addresses,json=previousAddresses,proto3" json:"previous_addresses,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_examples_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{13}
}

func (x *UserProfile) GetPerson() *Person {
	if x != nil {
		return x.Person
	}
	return nil
}

func (x *UserProfile) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UserProfile) GetInterests() []string {
	if x != nil {
		return x.Interests
	}
	return nil
}

func (x *UserProfile) GetPreferences() map[string]string {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *UserProfile) GetPreviousAddresses() []*Address {
	if x != nil {
		return x.PreviousAddresses
	}
	return nil
}

type GamePlayer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Handle        string                 `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Rating        int32                  `protobuf:"zigzag32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	RecentScores  []int32                `protobuf:"zigzag32,4,rep,packed,name=recent_scores,json=recentScores,proto3" json:"recent_scores,omitempty"`
	Inventory     map[string]uint32      `protobuf:"bytes,5,rep,name=inventory,proto3" json:"inventory,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamePlayer) Reset() {
	*x = GamePlayer{}
	mi := &file_examples_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamePlayer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamePlayer) ProtoMessage() {}

func (x *GamePlayer) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamePlayer.ProtoReflect.Descriptor instead.
func (*GamePlayer) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{14}
}

func (x *GamePlayer) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GamePlayer) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *GamePlayer) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GamePlayer) GetRecentScores() []int32 {
	if x != nil {
		return x.RecentScores
	}
	return nil
}

func (x *GamePlayer) GetInventory() map[string]uint32 {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GameMatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Players          []*GamePlayer          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	RoundDurationsMs []uint32               `protobuf:"varint,3,rep,packed,name=round_durations_ms,json=roundDurationsMs,proto3" json:"round_durations_ms,omitempty"`
	WinnerId         uint64                 `protobuf:"varint,4,opt,name=winner_id,json=winnerId,proto3" json:"winner_id,omitempty"`
	MapName          string                 `protobuf:"bytes,5,opt,name=map_name,json=mapName,proto3" json:"map_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameMatch) Reset() {
	*x = GameMatch{}
	mi := &file_examples_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMatch) ProtoMessage() {}

func (x *GameMatch) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMatch.ProtoReflect.Descriptor instead.
func (*GameMatch) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{15}
}

func (x *GameMatch) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameMatch) GetPlayers() []*GamePlayer {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameMatch) GetRoundDurationsMs() []uint32 {
	if x != nil {
		return x.RoundDurationsMs
	}
	return nil
}

func (x *GameMatch) GetWinnerId() uint64 {
	if x != nil {
		return x.WinnerId
	}
	return 0
}

func (x *GameMatch) GetMapName() string {
	if x != nil {
		return x.MapName
	}
	return ""
}

type MetricPoint struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Value           float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Annotations     []string               `protobuf:"bytes,3,rep,name=annotations,proto3" json:"annotations,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_examples_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{16}
}

func (x *MetricPoint) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetAnnotations() []string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type MetricSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dimensions    map[string]string      `protobuf:"bytes,2,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points        []*MetricPoint         `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	Unit          string                 `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_examples_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricSeries.ProtoReflect.Descriptor instead.
func (*MetricSeries) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{17}
}

func (x *MetricSeries) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricSeries) GetDimensions() map[string]string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *MetricSeries) GetPoints() []*MetricPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

func (x *MetricSeries) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type LogEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnixMs int64                  `protobuf:"varint,1,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Level           string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields          map[string]string      `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TraceId         []byte                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	StackFrames     []string               `protobuf:"bytes,6,rep,name=stack_frames,json=stackFrames,proto3" json:"stack_frames,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_examples_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{18}
}

func (x *LogEvent) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEvent) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *LogEvent) GetStackFrames() []string {
	if x != nil {
		return x.StackFrames
	}
	return nil
}

type PortfolioPosition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Symbol          string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	QuantityMicros  int64                  `protobuf:"zigzag64,2,opt,name=quantity_micros,json=quantityMicros,proto3" json:"quantity_micros,omitempty"`
	CostBasisMicros int64                  `protobuf:"zigzag64,3,opt,name=cost_basis_micros,json=costBasisMicros,proto3" json:"cost_basis_micros,omitempty"`
	MarketPrice     float64                `protobuf:"fixed64,4,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	DailyPnlMicros  []int64                `protobuf:"zigzag64,5,rep,packed,name=daily_pnl_micros,json=dailyPnlMicros,proto3" json:"daily_pnl_micros,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PortfolioPosition) Reset() {
	*x = PortfolioPosition{}
	mi := &file_examples_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioPosition) ProtoMessage() {}

func (x *PortfolioPosition) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioPosition.ProtoReflect.Descriptor instead.
func (*PortfolioPosition) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{19}
}

func (x *PortfolioPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PortfolioPosition) GetQuantityMicros() int64 {
	if x != nil {
		return x.QuantityMicros
	}
	return 0
}

func (x *PortfolioPosition) GetCostBasisMicros() int64 {
	if x != nil {
		return x.CostBasisMicros
	}
	return 0
}

func (x *PortfolioPosition) GetMarketPrice() float64 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *PortfolioPosition) GetDailyPnlMicros() []int64 {
	if x != nil {
		return x.DailyPnlMicros
	}
	return nil
}

type Portfolio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     uint64                 `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Owner         *Person                `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Positions     []*PortfolioPosition   `protobuf:"bytes,3,rep,name=positions,proto3" json:"positions,omitempty"`
	CashMicros    map[string]int64       `protobuf:"bytes,4,rep,name=cash_micros,json=cashMicros,proto3" json:"cash_micros,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"zigzag64,2,opt,name=value"`
	UpdatedUnix   int64                  `protobuf:"varint,5,opt,name=updated_unix,json=updatedUnix,proto3" json:"updated_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Portfolio) Reset() {
	*x = Portfolio{}
	mi := &file_examples_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Portfolio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Portfolio) ProtoMessage() {}

func (x *Portfolio) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Portfolio.ProtoReflect.Descriptor instead.
func (*Portfolio) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{20}
}

func (x *Portfolio) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Portfolio) GetOwner() *Person {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Portfolio) GetPositions() []*PortfolioPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Portfolio) GetCashMicros() map[string]int64 {
	if x != nil {
		return x.CashMicros
	}
	return nil
}

func (x *Portfolio) GetUpdatedUnix() int64 {
	if x != nil {
		return x.UpdatedUnix
	}
	return 0
}

// BenchmarkCorpus batches every example type so Colbin can use its intended
// columnar slice layout while Protobuf uses its normal repeated-message layout.
type BenchmarkCorpus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Addresses          []*Address             `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	People             []*Person              `protobuf:"bytes,2,rep,name=people,proto3" json:"people,omitempty"`
	Companies          []*Company             `protobuf:"bytes,3,rep,name=companies,proto3" json:"companies,omitempty"`
	Products           []*Product             `protobuf:"bytes,4,rep,name=products,proto3" json:"products,omitempty"`
	OrderLines         []*OrderLine           `protobuf:"bytes,5,rep,name=order_lines,json=orderLines,proto3" json:"order_lines,omitempty"`
	Orders             []*Order               `protobuf:"bytes,6,rep,name=orders,proto3" json:"orders,omitempty"`
	Invoices           []*Invoice             `protobuf:"bytes,7,rep,name=invoices,proto3" json:"invoices,omitempty"`
	SensorReadings     []*SensorReading       `protobuf:"bytes,8,rep,name=sensor_readings,json=sensorReadings,proto3" json:"sensor_readings,omitempty"`
	WeatherSamples     []*WeatherSample       `protobuf:"bytes,9,rep,name=weather_samples,json=weatherSamples,proto3" json:"weather_samples,omitempty"`
	GeoPoints          []*GeoPoint            `protobuf:"bytes,10,rep,name=geo_points,json=geoPoints,proto3" json:"geo_points,omitempty"`
	Routes             []*Route               `protobuf:"bytes,11,rep,name=routes,proto3" json:"routes,omitempty"`
	BlogPosts          []*BlogPost            `protobuf:"bytes,12,rep,name=blog_posts,json=blogPosts,proto3" json:"blog_posts,omitempty"`
	Comments           []*Comment             `protobuf:"bytes,13,rep,name=comments,proto3" json:"comments,omitempty"`
	UserProfiles       []*UserProfile         `protobuf:"bytes,14,rep,name=user_profiles,json=userProfiles,proto3" json:"user_profiles,omitempty"`
	GamePlayers        []*GamePlayer          `protobuf:"bytes,15,rep,name=game_players,json=gamePlayers,proto3" json:"game_players,omitempty"`
	GameMatches        []*GameMatch           `protobuf:"bytes,16,rep,name=game_matches,json=gameMatches,proto3" json:"game_matches,omitempty"`
	MetricPoints       []*MetricPoint         `protobuf:"bytes,17,rep,name=metric_points,json=metricPoints,proto3" json:"metric_points,omitempty"`
	MetricSeries       []*MetricSeries        `protobuf:"bytes,18,rep,name=metric_series,json=metricSeries,proto3" json:"metric_series,omitempty"`
	LogEvents          []*LogEvent            `protobuf:"bytes,19,rep,name=log_events,json=logEvents,proto3" json:"log_events,omitempty"`
	PortfolioPositions []*PortfolioPosition   `protobuf:"bytes,20,rep,name=portfolio_positions,json=portfolioPositions,proto3" json:"portfolio_positions,omitempty"`
	Portfolios         []*Portfolio           `protobuf:"bytes,21,rep,name=portfolios,proto3" json:"portfolios,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BenchmarkCorpus) Reset() {
	*x = BenchmarkCorpus{}
	mi := &file_examples_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BenchmarkCorpus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BenchmarkCorpus) ProtoMessage() {}

func (x *BenchmarkCorpus) ProtoReflect() protoreflect.Message {
	mi := &file_examples_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BenchmarkCorpus.ProtoReflect.Descriptor instead.
func (*BenchmarkCorpus) Descriptor() ([]byte, []int) {
	return file_examples_proto_rawDescGZIP(), []int{21}
}

func (x *BenchmarkCorpus) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *BenchmarkCorpus) GetPeople() []*Person {
	if x != nil {
		return x.People
	}
	return nil
}

func (x *BenchmarkCorpus) GetCompanies() []*Company {
	if x != nil {
		return x.Companies
	}
	return nil
}

func (x *BenchmarkCorpus) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *BenchmarkCorpus) GetOrderLines() []*OrderLine {
	if x != nil {
		return x.OrderLines
	}
	return nil
}

func (x *BenchmarkCorpus) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *BenchmarkCorpus) GetInvoices() []*Invoice {
	if x != nil {
		return x.Invoices
	}
	return nil
}

func (x *BenchmarkCorpus) GetSensorReadings() []*SensorReading {
	if x != nil {
		return x.SensorReadings
	}
	return nil
}

func (x *BenchmarkCorpus) GetWeatherSamples() []*WeatherSample {
	if x != nil {
		return x.WeatherSamples
	}
	return nil
}

func (x *BenchmarkCorpus) GetGeoPoints() []*GeoPoint {
	if x != nil {
		return x.GeoPoints
	}
	return nil
}

func (x *BenchmarkCorpus) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *BenchmarkCorpus) GetBlogPosts() []*BlogPost {
	if x != nil {
		return x.BlogPosts
	}
	return nil
}

func (x *BenchmarkCorpus) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *BenchmarkCorpus) GetUserProfiles() []*UserProfile {
	if x != nil {
		return x.UserProfiles
	}
	return nil
}

func (x *BenchmarkCorpus) GetGamePlayers() []*GamePlayer {
	if x != nil {
		return x.GamePlayers
	}
	return nil
}

func (x *BenchmarkCorpus) GetGameMatches() []*GameMatch {
	if x != nil {
		return x.GameMatches
	}
	return nil
}

func (x *BenchmarkCorpus) GetMetricPoints() []*MetricPoint {
	if x != nil {
		return x.MetricPoints
	}
	return nil
}

func (x *BenchmarkCorpus) GetMetricSeries() []*MetricSeries {
	if x != nil {
		return x.MetricSeries
	}
	return nil
}

func (x *BenchmarkCorpus) GetLogEvents() []*LogEvent {
	if x != nil {
		return x.LogEvents
	}
	return nil
}

func (x *BenchmarkCorpus) GetPortfolioPositions() []*PortfolioPosition {
	if x != nil {
		return x.PortfolioPositions
	}
	return nil
}

func (x *BenchmarkCorpus) GetPortfolios() []*Portfolio {
	if x != nil {
		return x.Portfolios
	}
	return nil
}

var File_examples_proto protoreflect.FileDescriptor

const file_examples_proto_rawDesc = "" +
	"\n" +
	"\x0eexamples.proto\x12\x11colbin.comparison\"\xaa\x01\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x1a\n" +
	"\blatitude\x18\x05 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x06 \x01(\x01R\tlongitude\"\xc5\x01\n" +
	"\x06Person\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active\x12\x16\n" +
	"\x06emails\x18\x05 \x03(\tR\x06emails\x124\n" +
	"\aaddress\x18\x06 \x01(\v2\x1a.colbin.comparison.AddressR\aaddress\x12\x1f\n" +
	"\vavatar_hash\x18\a \x01(\fR\n" +
	"avatarHash\"\xfd\x01\n" +
	"\aCompany\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bindustry\x18\x03 \x01(\tR\bindustry\x127\n" +
	"\temployees\x18\x04 \x03(\v2\x19.colbin.comparison.PersonR\temployees\x12>\n" +
	"\x06labels\x18\x05 \x03(\v2&.colbin.comparison.Company.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa1\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x12R\n" +
	"priceCents\x12\x14\n" +
	"\x05stock\x18\x05 \x01(\rR\x05stock\x12\x1e\n" +
	"\n" +
	"categories\x18\x06 \x03(\tR\n" +
	"categories\x12J\n" +
	"\n" +
	"attributes\x18\a \x03(\v2*.colbin.comparison.Product.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaa\x01\n" +
	"\tOrderLine\x124\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.colbin.comparison.ProductR\aproduct\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x03 \x01(\x12R\x0eunitPriceCents\x12!\n" +
	"\fdiscount_bps\x18\x04 \x03(\x11R\vdiscountBps\"\x84\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x125\n" +
	"\bcustomer\x18\x02 \x01(\v2\x19.colbin.comparison.PersonR\bcustomer\x122\n" +
	"\x05lines\x18\x03 \x03(\v2\x1c.colbin.comparison.OrderLineR\x05lines\x12E\n" +
	"\x10shipping_address\x18\x04 \x01(\v2\x1a.colbin.comparison.AddressR\x0fshippingAddress\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fcreated_unix\x18\x06 \x01(\x03R\vcreatedUnix\"\xe0\x01\n" +
	"\aInvoice\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12.\n" +
	"\x05order\x18\x02 \x01(\v2\x18.colbin.comparison.OrderR\x05order\x12%\n" +
	"\x0esubtotal_cents\x18\x03 \x01(\x12R\rsubtotalCents\x12\x1b\n" +
	"\ttax_cents\x18\x04 \x01(\x12R\btaxCents\x12\x1f\n" +
	"\vtotal_cents\x18\x05 \x01(\x12R\n" +
	"totalCents\x12\x12\n" +
	"\x04paid\x18\x06 \x01(\bR\x04paid\x12\x14\n" +
	"\x05notes\x18\a \x03(\tR\x05notes\"\xb2\x01\n" +
	"\rSensorReading\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\x04R\bsensorId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12\x18\n" +
	"\asamples\x18\x05 \x03(\x11R\asamples\x12\x14\n" +
	"\x05valid\x18\x06 \x01(\bR\x05valid\"\xf7\x01\n" +
	"\rWeatherSample\x12\x18\n" +
	"\astation\x18\x01 \x01(\tR\astation\x12%\n" +
	"\x0etimestamp_unix\x18\x02 \x01(\x03R\rtimestampUnix\x12#\n" +
	"\rtemperature_c\x18\x03 \x01(\x02R\ftemperatureC\x12)\n" +
	"\x10humidity_percent\x18\x04 \x01(\x02R\x0fhumidityPercent\x12\x19\n" +
	"\bwind_kph\x18\x05 \x01(\x02R\awindKph\x12:\n" +
	"\asensors\x18\x06 \x03(\v2 .colbin.comparison.SensorReadingR\asensors\"{\n" +
	"\bGeoPoint\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x01R\tlongitude\x12\x1f\n" +
	"\velevation_m\x18\x03 \x01(\x11R\n" +
	"elevationM\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"\xa8\x01\n" +
	"\x05Route\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\x06points\x18\x03 \x03(\v2\x1b.colbin.comparison.GeoPointR\x06points\x122\n" +
	"\x15segment_durations_sec\x18\x04 \x03(\rR\x13segmentDurationsSec\x12\x12\n" +
	"\x04toll\x18\x05 \x01(\bR\x04toll\"\xb2\x01\n" +
	"\bBlogPost\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x121\n" +
	"\x06author\x18\x02 \x01(\v2\x19.colbin.comparison.PersonR\x06author\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12%\n" +
	"\x0epublished_unix\x18\x06 \x01(\x03R\rpublishedUnix\"\xb4\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\x04R\x06postId\x121\n" +
	"\x06author\x18\x03 \x01(\v2\x19.colbin.comparison.PersonR\x06author\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1b\n" +
	"\treply_ids\x18\x05 \x03(\x04R\breplyIds\x12\x1c\n" +
	"\tmoderated\x18\x06 \x01(\bR\tmoderated\"\xda\x02\n" +
	"\vUserProfile\x121\n" +
	"\x06person\x18\x01 \x01(\v2\x19.colbin.comparison.PersonR\x06person\x12\x1c\n" +
	"\tbiography\x18\x02 \x01(\tR\tbiography\x12\x1c\n" +
	"\tinterests\x18\x03 \x03(\tR\tinterests\x12Q\n" +
	"\vpreferences\x18\x04 \x03(\v2/.colbin.comparison.UserProfile.PreferencesEntryR\vpreferences\x12I\n" +
	"\x12previous_addresses\x18\x05 \x03(\v2\x1a.colbin.comparison.AddressR\x11previousAddresses\x1a>\n" +
	"\x10PreferencesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfb\x01\n" +
	"\n" +
	"GamePlayer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x16\n" +
	"\x06handle\x18\x02 \x01(\tR\x06handle\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x11R\x06rating\x12#\n" +
	"\rrecent_scores\x18\x04 \x03(\x11R\frecentScores\x12J\n" +
	"\tinventory\x18\x05 \x03(\v2,.colbin.comparison.GamePlayer.InventoryEntryR\tinventory\x1a<\n" +
	"\x0eInventoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"\xba\x01\n" +
	"\tGameMatch\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x127\n" +
	"\aplayers\x18\x02 \x03(\v2\x1d.colbin.comparison.GamePlayerR\aplayers\x12,\n" +
	"\x12round_durations_ms\x18\x03 \x03(\rR\x10roundDurationsMs\x12\x1b\n" +
	"\twinner_id\x18\x04 \x01(\x04R\bwinnerId\x12\x19\n" +
	"\bmap_name\x18\x05 \x01(\tR\amapName\"q\n" +
	"\vMetricPoint\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x12 \n" +
	"\vannotations\x18\x03 \x03(\tR\vannotations\"\xfe\x01\n" +
	"\fMetricSeries\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12O\n" +
	"\n" +
	"dimensions\x18\x02 \x03(\v2/.colbin.comparison.MetricSeries.DimensionsEntryR\n" +
	"dimensions\x126\n" +
	"\x06points\x18\x03 \x03(\v2\x1e.colbin.comparison.MetricPointR\x06points\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x1a=\n" +
	"\x0fDimensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa0\x02\n" +
	"\bLogEvent\x12*\n" +
	"\x11timestamp_unix_ms\x18\x01 \x01(\x03R\x0ftimestampUnixMs\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12?\n" +
	"\x06fields\x18\x04 \x03(\v2'.colbin.comparison.LogEvent.FieldsEntryR\x06fields\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\fR\atraceId\x12!\n" +
	"\fstack_frames\x18\x06 \x03(\tR\vstackFrames\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x11PortfolioPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x0fquantity_micros\x18\x02 \x01(\x12R\x0equantityMicros\x12*\n" +
	"\x11cost_basis_micros\x18\x03 \x01(\x12R\x0fcostBasisMicros\x12!\n" +
	"\fmarket_price\x18\x04 \x01(\x01R\vmarketPrice\x12(\n" +
	"\x10daily_pnl_micros\x18\x05 \x03(\x12R\x0edailyPnlMicros\"\xd0\x02\n" +
	"\tPortfolio\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x04R\taccountId\x12/\n" +
	"\x05owner\x18\x02 \x01(\v2\x19.colbin.comparison.PersonR\x05owner\x12B\n" +
	"\tpositions\x18\x03 \x03(\v2$.colbin.comparison.PortfolioPositionR\tpositions\x12M\n" +
	"\vcash_micros\x18\x04 \x03(\v2,.colbin.comparison.Portfolio.CashMicrosEntryR\n" +
	"cashMicros\x12!\n" +
	"\fupdated_unix\x18\x05 \x01(\x03R\vupdatedUnix\x1a=\n" +
	"\x0fCashMicrosEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x12R\x05value:\x028\x01\"\xb5\n" +
	"\n" +
	"\x0fBenchmarkCorpus\x128\n" +
	"\taddresses\x18\x01 \x03(\v2\x1a.colbin.comparison.AddressR\taddresses\x121\n" +
	"\x06people\x18\x02 \x03(\v2\x19.colbin.comparison.PersonR\x06people\x128\n" +
	"\tcompanies\x18\x03 \x03(\v2\x1a.colbin.comparison.CompanyR\tcompanies\x126\n" +
	"\bproducts\x18\x04 \x03(\v2\x1a.colbin.comparison.ProductR\bproducts\x12=\n" +
	"\vorder_lines\x18\x05 \x03(\v2\x1c.colbin.comparison.OrderLineR\n" +
	"orderLines\x120\n" +
	"\x06orders\x18\x06 \x03(\v2\x18.colbin.comparison.OrderR\x06orders\x126\n" +
	"\binvoices\x18\a \x03(\v2\x1a.colbin.comparison.InvoiceR\binvoices\x12I\n" +
	"\x0fsensor_readings\x18\b \x03(\v2 .colbin.comparison.SensorReadingR\x0esensorReadings\x12I\n" +
	"\x0fweather_samples\x18\t \x03(\v2 .colbin.comparison.WeatherSampleR\x0eweatherSamples\x12:\n" +
	"\n" +
	"geo_points\x18\n" +
	" \x03(\v2\x1b.colbin.comparison.GeoPointR\tgeoPoints\x120\n" +
	"\x06routes\x18\v \x03(\v2\x18.colbin.comparison.RouteR\x06routes\x12:\n" +
	"\n" +
	"blog_posts\x18\f \x03(\v2\x1b.colbin.comparison.BlogPostR\tblogPosts\x126\n" +
	"\bcomments\x18\r \x03(\v2\x1a.colbin.comparison.CommentR\bcomments\x12C\n" +
	"\ruser_profiles\x18\x0e \x03(\v2\x1e.colbin.comparison.UserProfileR\fuserProfiles\x12@\n" +
	"\fgame_players\x18\x0f \x03(\v2\x1d.colbin.comparison.GamePlayerR\vgamePlayers\x12?\n" +
	"\fgame_matches\x18\x10 \x03(\v2\x1c.colbin.comparison.GameMatchR\vgameMatches\x12C\n" +
	"\rmetric_points\x18\x11 \x03(\v2\x1e.colbin.comparison.MetricPointR\fmetricPoints\x12D\n" +
	"\rmetric_series\x18\x12 \x03(\v2\x1f.colbin.comparison.MetricSeriesR\fmetricSeries\x12:\n" +
	"\n" +
	"log_events\x18\x13 \x03(\v2\x1b.colbin.comparison.LogEventR\tlogEvents\x12U\n" +
	"\x13portfolio_positions\x18\x14 \x03(\v2$.colbin.comparison.PortfolioPositionR\x12portfolioPositions\x12<\n" +
	"\n" +
	"portfolios\x18\x15 \x03(\v2\x1c.colbin.comparison.PortfolioR\n" +
	"portfoliosB&Z$github.com/ivanjoz/colbin/comparisonb\x06proto3"

var (
	file_examples_proto_rawDescOnce sync.Once
	file_examples_proto_rawDescData []byte
)

func file_examples_proto_rawDescGZIP() []byte {
	file_examples_proto_rawDescOnce.Do(func() {
		file_examples_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_proto_rawDesc), len(file_examples_proto_rawDesc)))
	})
	return file_examples_proto_rawDescData
}

var file_examples_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_examples_proto_goTypes = []any{
	(*Address)(nil),           // 0: colbin.comparison.Address
	(*Person)(nil),            // 1: colbin.comparison.Person
	(*Company)(nil),           // 2: colbin.comparison.Company
	(*Product)(nil),           // 3: colbin.comparison.Product
	(*OrderLine)(nil),         // 4: colbin.comparison.OrderLine
	(*Order)(nil),             // 5: colbin.comparison.Order
	(*Invoice)(nil),           // 6: colbin.comparison.Invoice
	(*SensorReading)(nil),     // 7: colbin.comparison.SensorReading
	(*WeatherSample)(nil),     // 8: colbin.comparison.WeatherSample
	(*GeoPoint)(nil),          // 9: colbin.comparison.GeoPoint
	(*Route)(nil),             // 10: colbin.comparison.Route
	(*BlogPost)(nil),          // 11: colbin.comparison.BlogPost
	(*Comment)(nil),           // 12: colbin.comparison.Comment
	(*UserProfile)(nil),       // 13: colbin.comparison.UserProfile
	(*GamePlayer)(nil),        // 14: colbin.comparison.GamePlayer
	(*GameMatch)(nil),         // 15: colbin.comparison.GameMatch
	(*MetricPoint)(nil),       // 16: colbin.comparison.MetricPoint
	(*MetricSeries)(nil),      // 17: colbin.comparison.MetricSeries
	(*LogEvent)(nil),          // 18: colbin.comparison.LogEvent
	(*PortfolioPosition)(nil), // 19: colbin.comparison.PortfolioPosition
	(*Portfolio)(nil),         // 20: colbin.comparison.Portfolio
	(*BenchmarkCorpus)(nil),   // 21: colbin.comparison.BenchmarkCorpus
	nil,                       // 22: colbin.comparison.Company.LabelsEntry
	nil,                       // 23: colbin.comparison.Product.AttributesEntry
	nil,                       // 24: colbin.comparison.UserProfile.PreferencesEntry
	nil,                       // 25: colbin.comparison.GamePlayer.InventoryEntry
	nil,                       // 26: colbin.comparison.MetricSeries.DimensionsEntry
	nil,                       // 27: colbin.comparison.LogEvent.FieldsEntry
	nil,                       // 28: colbin.comparison.Portfolio.CashMicrosEntry
}
var file_examples_proto_depIdxs = []int32{
	0,  // 0: colbin.comparison.Person.address:type_name -> colbin.comparison.Address
	1,  // 1: colbin.comparison.Company.employees:type_name -> colbin.comparison.Person
	22, // 2: colbin.comparison.Company.labels:type_name -> colbin.comparison.Company.LabelsEntry
	23, // 3: colbin.comparison.Product.attributes:type_name -> colbin.comparison.Product.AttributesEntry
	3,  // 4: colbin.comparison.OrderLine.product:type_name -> colbin.comparison.Product
	1,  // 5: colbin.comparison.Order.customer:type_name -> colbin.comparison.Person
	4,  // 6: colbin.comparison.Order.lines:type_name -> colbin.comparison.OrderLine
	0,  // 7: colbin.comparison.Order.shipping_address:type_name -> colbin.comparison.Address
	5,  // 8: colbin.comparison.Invoice.order:type_name -> colbin.comparison.Order
	7,  // 9: colbin.comparison.WeatherSample.sensors:type_name -> colbin.comparison.SensorReading
	9,  // 10: colbin.comparison.Route.points:type_name -> colbin.comparison.GeoPoint
	1,  // 11: colbin.comparison.BlogPost.author:type_name -> colbin.comparison.Person
	1,  // 12: colbin.comparison.Comment.author:type_name -> colbin.comparison.Person
	1,  // 13: colbin.comparison.UserProfile.person:type_name -> colbin.comparison.Person
	24, // 14: colbin.comparison.UserProfile.preferences:type_name -> colbin.comparison.UserProfile.PreferencesEntry
	0,  // 15: colbin.comparison.UserProfile.previous_addresses:type_name -> colbin.comparison.Address
	25, // 16: colbin.comparison.GamePlayer.inventory:type_name -> colbin.comparison.GamePlayer.InventoryEntry
	14, // 17: colbin.comparison.GameMatch.players:type_name -> colbin.comparison.GamePlayer
	26, // 18: colbin.comparison.MetricSeries.dimensions:type_name -> colbin.comparison.MetricSeries.DimensionsEntry
	16, // 19: colbin.comparison.MetricSeries.points:type_name -> colbin.comparison.MetricPoint
	27, // 20: colbin.comparison.LogEvent.fields:type_name -> colbin.comparison.LogEvent.FieldsEntry
	1,  // 21: colbin.comparison.Portfolio.owner:type_name -> colbin.comparison.Person
	19, // 22: colbin.comparison.Portfolio.positions:type_name -> colbin.comparison.PortfolioPosition
	28, // 23: colbin.comparison.Portfolio.cash_micros:type_name -> colbin.comparison.Portfolio.CashMicrosEntry
	0,  // 24: colbin.comparison.BenchmarkCorpus.addresses:type_name -> colbin.comparison.Address
	1,  // 25: colbin.comparison.BenchmarkCorpus.people:type_name -> colbin.comparison.Person
	2,  // 26: colbin.comparison.BenchmarkCorpus.companies:type_name -> colbin.comparison.Company
	3,  // 27: colbin.comparison.BenchmarkCorpus.products:type_name -> colbin.comparison.Product
	4,  // 28: colbin.comparison.BenchmarkCorpus.order_lines:type_name -> colbin.comparison.OrderLine
	5,  // 29: colbin.comparison.BenchmarkCorpus.orders:type_name -> colbin.comparison.Order
	6,  // 30: colbin.comparison.BenchmarkCorpus.invoices:type_name -> colbin.comparison.Invoice
	7,  // 31: colbin.comparison.BenchmarkCorpus.sensor_readings:type_name -> colbin.comparison.SensorReading
	8,  // 32: colbin.comparison.BenchmarkCorpus.weather_samples:type_name -> colbin.comparison.WeatherSample
	9,  // 33: colbin.comparison.BenchmarkCorpus.geo_points:type_name -> colbin.comparison.GeoPoint
	10, // 34: colbin.comparison.BenchmarkCorpus.routes:type_name -> colbin.comparison.Route
	11, // 35: colbin.comparison.BenchmarkCorpus.blog_posts:type_name -> colbin.comparison.BlogPost
	12, // 36: colbin.comparison.BenchmarkCorpus.comments:type_name -> colbin.comparison.Comment
	13, // 37: colbin.comparison.BenchmarkCorpus.user_profiles:type_name -> colbin.comparison.UserProfile
	14, // 38: colbin.comparison.BenchmarkCorpus.game_players:type_name -> colbin.comparison.GamePlayer
	15, // 39: colbin.comparison.BenchmarkCorpus.game_matches:type_name -> colbin.comparison.GameMatch
	16, // 40: colbin.comparison.BenchmarkCorpus.metric_points:type_name -> colbin.comparison.MetricPoint
	17, // 41: colbin.comparison.BenchmarkCorpus.metric_series:type_name -> colbin.comparison.MetricSeries
	18, // 42: colbin.comparison.BenchmarkCorpus.log_events:type_name -> colbin.comparison.LogEvent
	19, // 43: colbin.comparison.BenchmarkCorpus.portfolio_positions:type_name -> colbin.comparison.PortfolioPosition
	20, // 44: colbin.comparison.BenchmarkCorpus.portfolios:type_name -> colbin.comparison.Portfolio
	45, // [45:45] is the sub-list for method output_type
	45, // [45:45] is the sub-list for method input_type
	45, // [45:45] is the sub-list for extension type_name
	45, // [45:45] is the sub-list for extension extendee
	0,  // [0:45] is the sub-list for field type_name
}

func init() { file_examples_proto_init() }
func file_examples_proto_init() {
	if File_examples_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_proto_rawDesc), len(file_examples_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_proto_goTypes,
		DependencyIndexes: file_examples_proto_depIdxs,
		MessageInfos:      file_examples_proto_msgTypes,
	}.Build()
	File_examples_proto = out.File
	file_examples_proto_goTypes = nil
	file_examples_proto_depIdxs = nil
}
